### ISSUE TITLE
Meme Generator 

### ISSUE THREAD

**Issue by khushi-purwar** [khushi-purwar/WebDev-ProjectKart#1]
**Project title**
Meme Generator

**Project Description**
Build a responsive meme generator that will allow to create custom memes by adding funny or sarcastic caption to the images.

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by nirbhay12345** [comment]
I am new to open source.

I suppose ICC'21 is over.

Instead this could be contribution, so I am interested in this.

Can I work on this?

**Comment by khushi-purwar** [comment]
> I am new to open source.
> 
> I suppose ICC'21 is over.
> 
> Instead this could be contribution, so I am interested in this.
> 
> Can I work on this?

Yes, you can work on this issue.
