### ISSUE TITLE
Want to improve UI of color scheme switcher

### ISSUE THREAD

**Issue by Priyal168** [khushi-purwar/WebDev-ProjectKart#100]
**Project name**
Color Scheme Switcher

**Project link**
https://khushi-purwar.github.io/WebDev-ProjectKart/

**Improvements suggested**
Want to improve UI of the following by using:
HTML,
CSS,
JS

**Comment by Priyal168** [comment]
I am a contributor in GSOCC'22 please assign this to me

**Comment by khushi-purwar** [comment]
@Priyal168 you can start working on it

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by Priyal168** [comment]
@khushi-purwar sorry for being inactivte i will start working from today only
