### ISSUE TITLE
I want to add a Catch me if you can game 

### ISSUE THREAD

**Issue by Shreyaar12** [khushi-purwar/WebDev-ProjectKart#104]
**Project title**
Catch me if you can  

**Project Description**
A square that keeps moving across the screen as user tries to click on it and catch it. 
**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@Shreyaar12 you can start working on it

**Comment by Shreyaar12** [comment]
push access required to add the files
