### ISSUE TITLE
Google Photos Clone

### ISSUE THREAD

**Issue by XZANATOL** [khushi-purwar/WebDev-ProjectKart#1067]
**Project title**
Google Photos Clone

**Project Description**
Add Google Photos Clone

**Stack**:  

- [x] Html
- [x] CSS

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue?

**Comment by XZANATOL** [comment]
I'm already working on it.

**Comment by Sulagna-Dutta-Roy** [comment]
Okay then 👍
