### ISSUE TITLE
[Bug fix] in template_pull_request.md

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [khushi-purwar/WebDev-ProjectKart#107]
hi, there :smile: ,
In ur doc's file   PULL_REQUEST_TEMPLATE.md there is an grammatical error .. 
please assign this issue to me so that i can fixed it out .... 
As these doc's are very important and it gave bad impact on the Organisation.   

### GSSOC'22 contributor

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903
