### ISSUE TITLE
Add QR Code Generator 

### ISSUE THREAD

**Issue by SachinMittal1766** [khushi-purwar/WebDev-ProjectKart#1073]
**Project title**
QR Code Generator

**Project Description**
It will generate QR code for text or link inserted by user.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

**Comment by gurjeetsinghvirdee** [comment]
#1078
