### ISSUE TITLE
Want to add SVG generator

### ISSUE THREAD

**Issue by iamrahulmahato** [khushi-purwar/WebDev-ProjectKart#1074]
**Project title**
SVG generator

**Project Description**
Random SVG Generator is an one place destination to make your random cool svg for your profile pic or any other work.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript
- 
![Web capture_7-4-2022_55318_127 0 0 1 (1)](https://user-images.githubusercontent.com/49890655/166088321-6ee242e4-5780-4fba-becd-d0f3630957b6.jpeg)
![Web capture_7-4-2022_55339_127 0 0 1 (1)](https://user-images.githubusercontent.com/49890655/166088323-ef2d8956-1087-4bb2-9314-2448c41f9229.jpeg)

inspiration :- https://github.com/boringdesigners

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @iamrahulmahato

**Comment by aachal28** [comment]
Assign me this

**Comment by gurjeetsinghvirdee** [comment]
> Assign me this

@Mrjoy832 Assign karna hai?

**Comment by Mrjoy832** [comment]
> > Assign me this
> 
> @Mrjoy832 Assign karna hai?

New pr to allowed nehi hain..issue assign korke vi kya hoga?

**Comment by gurjeetsinghvirdee** [comment]
ye b shi hai 

@aachal28 sorry we are not accepting new PRs

**Comment by Mrjoy832** [comment]
> ye b shi hai
> 
> @aachal28 sorry we are not accepting new PRs

firse bki log vi start ho jayega
