### ISSUE TITLE
Want to change the UI of Tic Tac Toe game

### ISSUE THREAD

**Issue by iamrahulmahato** [khushi-purwar/WebDev-ProjectKart#1075]
**Project name**
Tic-Tac-Toe

**Project link**
(Provide project link over here)](https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Tic-Tac-Toe

**Improvements suggested**
- Change the Whole UI of tic tac toe game
- will add two new cards for win and loss 

demo :- 
![0000001](https://user-images.githubusercontent.com/49890655/166088847-7dda1a13-3688-4a24-b042-3ab2e538f1ff.jpeg)
![000000002](https://user-images.githubusercontent.com/49890655/166088864-bcfa0f4c-aa04-4866-84ed-d5074155f335.jpeg)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @iamrahulmahato

**Comment by iamrahulmahato** [comment]
@gurjeetsinghvirdee The PR is made #1101 .
