### ISSUE TITLE
Modifiy UI of main page

### ISSUE THREAD

**Issue by SachinMittal1766** [khushi-purwar/WebDev-ProjectKart#1079]
**Project name**
Main webpage

**Project link**
(Provide project link over here)

**Improvements suggested**
I would like to improve CSS & UI. So as to make it more interactive.

**Comment by gurjeetsinghvirdee** [comment]
close this issue bro because we don't want to deploy this repo just add projects

**Comment by gurjeetsinghvirdee** [comment]
before making PR put your changes here wanna look @SachinMittal1766

**Comment by SachinMittal1766** [comment]
Webpage UI:
![Screenshot (1011)](https://user-images.githubusercontent.com/82721772/166104442-6c35296d-cc4d-4279-8b37-465e90f8a89a.png)

If you @gurjeetsinghvirdee like, I will make a PR for the same.

**Comment by gurjeetsinghvirdee** [comment]
> Webpage UI:
> ![Screenshot (1011)](https://user-images.githubusercontent.com/82721772/166104442-6c35296d-cc4d-4279-8b37-465e90f8a89a.png)
> 
> If you @gurjeetsinghvirdee like, I will make a PR for the same.

It looks great you can make a PR
