### ISSUE TITLE
Music App

### ISSUE THREAD

**Issue by Kumar-Ankit56** [khushi-purwar/WebDev-ProjectKart#1084]
**Project title**
Music App

**Project Description**
### The idea behind this project
Now a days we have multiple Music App player through which we used to listen Music daily some of them are Spotify  ganna and many more. So I decided to build a similar kind of function App.
### How does it work
Just load the project file in the browser and enjoy with Music player just by pressing play button and it will have all the basic principles that we used to see in a normal Music player.
You have access to play the song with lyrics.

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

for more details please refer to the attached Ss
Soon there will be link for 
Ss

**Comment by gurjeetsinghvirdee** [comment]
Already in project repo
