### ISSUE TITLE
I will add a Jumping square animation project created with HTML and CSS to the web dev projectKart repository.

### ISSUE THREAD

**Issue by AmolShelke2** [khushi-purwar/WebDev-ProjectKart#1086]
**Project title**
(Jumping square animation.)

**Project Description**
(it is a very simple and useful project for beginners to understand how the keyframes functions work in CSS I was not good at animations but after creating some projects with animation I'm good at it now this project is created with HTML and CSS. also adding the demo below once go through it.)

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
<hr>

https://user-images.githubusercontent.com/95171638/166110377-374263de-5859-4f36-9a14-1ee9a5424362.mp4

@gurjeetsinghvirdee kindly review this issue.

**Comment by gurjeetsinghvirdee** [comment]
You can't add same project to 3 different repos

**Comment by AmolShelke2** [comment]
Okayyy.
