### ISSUE TITLE
I want to add a animated background project.

### ISSUE THREAD

**Issue by AmolShelke2** [khushi-purwar/WebDev-ProjectKart#1100]
**Project title**
(animating background)

**Project Description**
(Hey, project admin I'm a GSSOC participant and I want to add an animated background project created with HTML and CSS it consists of animation transforms properties merely focused on CSS animation I'm attaching the demo below please go through it and assign me the issue to work on.)

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS

https://user-images.githubusercontent.com/95171638/165969529-fd3ae505-b1da-4f0a-b7ae-c902929a600f.mp4

@gurjeetsinghvirdee as you said that I cannot add the same project to the repository. this project is not added to any repository.
assign me this issue to work on.

**Comment by gurjeetsinghvirdee** [comment]
Copying project from same person everytime
https://www.youtube.com/watch?v=3kORIXnEg0I
