### ISSUE TITLE
Adding a Dice Game

### ISSUE THREAD

**Issue by itzwow** [khushi-purwar/WebDev-ProjectKart#114]
**Project title**
Want to add a Dice game

**Project Description**
there will be two dices. On clicking the play button it will generate random numbers from 1-6 and the dice having higher number will win or if same number comes then there will be draw.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

I am a GSSoC participant and want to contribute under GSSoC'22

**Comment by Srilakshmi-27** [comment]
**Project title:** 
Adding a Dice Game

**Project Description:** There will be two dice for Player 1 and Player 2. On clicking refresh or Play button, two random numbers will be generated between 1-6 and the die having greater number will win and if both numbers are equal then it will be a draw.

@khushi-purwar I am a GSSoC'22 participant and want to contribute to this. Kindly assign it to me.

**Comment by Simran2337** [comment]
Project title:
Throw a Dice

Project Description: There will be two dice for Player 1 and Player 2. On clicking Play button, two random numbers will be generated between 1-6 and the die having greater number will win and if both numbers are equal then it will be a draw.
Scores will be calculated accordingly

HTML
CSS
JS

@khushi-purwar I am a GSSoC'22 participant and want to contribute to this.
