### ISSUE TITLE
Want to Improve the ui of breakout game

### ISSUE THREAD

**Issue by iamrahulmahato** [khushi-purwar/WebDev-ProjectKart#1146]
**Project name**
Breakout game

**Project link**
https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Breakout%20Game

**Improvements suggested**
- improve UI
- add description in website (How To Play)

ss:
![Web capture_2-5-2022_181452_127 0 0 1](https://user-images.githubusercontent.com/49890655/166391745-a4de8a37-3d57-4603-9f10-1abd6143334d.jpeg)
![Web capture_2-5-2022_182241_127 0 0 1](https://user-images.githubusercontent.com/49890655/166391785-d37c7e0c-6e9b-412c-9561-a944e42cbb61.jpeg)

**Comment by gurjeetsinghvirdee** [comment]
@iamrahulmahato Assigned to u

**Comment by iamrahulmahato** [comment]
@gurjeetsinghvirdee the pr is made #1212
