### ISSUE TITLE
Airbnb Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [khushi-purwar/WebDev-ProjectKart#1158]
**Project title**
Airbnb Clone

**Project Description**
It's a Clone of the Airbnb website
**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] ReactJS

**Comment by LiQuiD-404** [comment]
@gurjeetsinghvirdee I am already working on a similar issue. #705 but I will be making this clone using HTML, CSS, and Javascript. I hope there will be no issue with that.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee I am already working on a similar issue. #705 but I will be making this clone using HTML, CSS, and Javascript. I hope there will be no issue with that.

My mind be like: Me ky Kru contributing chor du

**Comment by LiQuiD-404** [comment]
@gurjeetsinghvirdee  The languages are different so that should not be an issue. Please do not close.

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee The languages are different so that should not be an issue. Please do not close.

that's not an issue but we can't add same project twice

**Comment by LiQuiD-404** [comment]
> > @gurjeetsinghvirdee The languages are different so that should not be an issue. Please do not close.
> 
> that's not an issue but we can't add same project twice

😔 Then you work on this. I will find something else.

**Comment by LiQuiD-404** [comment]
@gurjeetsinghvirdee Lelo mai kuch aur bana dunga

**Comment by gurjeetsinghvirdee** [comment]
ni maine merge krdi h aur maine bna liya h kuch aur
