### ISSUE TITLE
HealthyZone...-website 

### ISSUE THREAD

**Issue by yash-25log** [khushi-purwar/WebDev-ProjectKart#1159]
Health care website with scroll effects

##tech stack-
HTML
CSS
js
https://healthcare-web.vercel.app/#

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee bhai github-action bot ke perms lelie kya?

**Comment by yash-25log** [comment]
> > @gurjeetsinghvirdee bhai github-action bot ke perms lelie kya?
> > 
> 
> Hta diye h maine, jab tak ek aur mentor koi active ni hoga workflow add ni hounge

Assign to kardo bhai

**Comment by gurjeetsinghvirdee** [comment]
Krdiya
