### ISSUE TITLE
Add an art gallery website

### ISSUE THREAD

**Issue by khushigupta123** [khushi-purwar/WebDev-ProjectKart#1199]
**Project title**
Art Gallery
**Project Description**
I want to create an art gallery website that contains following section:
- about us
- Our art works
- events and news
- contact us 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by coolblizzarts** [comment]
hello, can I work on this issue?
