### ISSUE TITLE
Sound Classifier Web App

### ISSUE THREAD

**Issue by shreya024** [khushi-purwar/WebDev-ProjectKart#1201]
**Project title**
Sound Classifier

**Project Description**
(Describe the project over here)
It takes input from microphone and then predicts when the user has spoken into words

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] CSS
- [x] ReactJS

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @shreya024
