### ISSUE TITLE
Making Alarm app

### ISSUE THREAD

**Issue by AastikSharma05** [khushi-purwar/WebDev-ProjectKart#1202]
**Project title**
Making a Alarm App website

**Project Description**
To make an alarm app using html,css and javascript

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by AastikSharma05** [comment]
@khushi-purwar

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @AastikSharma05
