### ISSUE TITLE
Adding a Main page 

### ISSUE THREAD

**Issue by Samikshyasahoo** [khushi-purwar/WebDev-ProjectKart#123]
**Project name**
(Add project name over here)

**Project link**
(Provide project link over here)

**Improvements suggested**
![Gssocprojectpic](https://user-images.githubusercontent.com/87387698/156296352-76a88a03-2008-42ee-b099-e1aaa68b6093.png)

can we make this as a home page by making grids of 22 projects .
If this kind of changes are possible to make, then I would like to work on it.

**Comment by Simran2337** [comment]
As a gssoc'22 participant, I am ready to take on this
please allow me, Thankyou

**Comment by shivananilisharma** [comment]
Kindly assign this issue to me
