### ISSUE TITLE
POLL UI 

### ISSUE THREAD

**Issue by Mrjoy832** [khushi-purwar/WebDev-ProjectKart#1230]
**Project title**
POLL UI 

**Project Description**
I want to add **POLL UI** which are likely used in  Telegram,Linkedin , Youtube using HTML,CSS,JS

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Mrjoy832

**Comment by Mrjoy832** [comment]
> Assigned u @Mrjoy832

Thank u
