### ISSUE TITLE
Netflix Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [khushi-purwar/WebDev-ProjectKart#1235]
**Project title**
Netflix Clone

**Project Description**
In this project React used

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] ReactJS

**Comment by gurjeetsinghvirdee** [comment]
> > **Project title** Netflix Clone
> > **Project Description** In this project MERN stack used
> > **Stack**: And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.
> > 
> > * [x]   ReactJS
> 
> complete clone with backend?

mind check krdiya utna ni ho pyga bs front end kiya hai template edit krne aaya that MERN see React 
possible hi ni h 2 din me MERN stack vo b netflix

**Comment by yash-25log** [comment]
hm
