### ISSUE TITLE
AI face detection

### ISSUE THREAD

**Issue by srinjoy-26** [khushi-purwar/WebDev-ProjectKart#1243]
**Project title**
AI face detection

**Project Description**
AI face detection

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] JavaScript

**Comment by gurjeetsinghvirdee** [comment]
glt bnda tag hogya tha glti se @srinjoy-26

**Comment by srinjoy-26** [comment]
koi ni veere

**Comment by navyasharma0203** [comment]
Can I work on this??

**Comment by srinjoy-26** [comment]
> Can I work on this??

Nope
