### ISSUE TITLE
Beauty store - ecommerce website 

### ISSUE THREAD

**Issue by yash-25log** [khushi-purwar/WebDev-ProjectKart#1250]
**Project title**
(Write project title over here)
An ecommerce website that can used by any cosmetic shop

No copyright
Free to use
**Project Description**
(Describe the project over here)

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee krdena Vai assign

**Comment by gurjeetsinghvirdee** [comment]
Assign toh h

**Comment by yash-25log** [comment]
Oh bhai lightening speed
