### ISSUE TITLE
WeatherApp -React JS

### ISSUE THREAD

**Issue by yash-25log** [khushi-purwar/WebDev-ProjectKart#1267]
converted the vue js weather app to react js one

uses same api

improved the ui tho

![image](https://user-images.githubusercontent.com/58944204/167106337-3c783b8d-9661-42a9-9924-6cd0a6bcf75a.png)

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @yash-25log
