### ISSUE TITLE
Create a UI Clone of Kookaburra

### ISSUE THREAD

**Issue by Kumar-laxmi** [khushi-purwar/WebDev-ProjectKart#1268]
**Project title**
UI Clone of Kookaburra

**Project Description**
Create a UI Clone of Kookaburra

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [X] JavaScript
- [ ] ReactJS

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Kumar-laxmi
