### ISSUE TITLE
Login Form Js Project

### ISSUE THREAD

**Issue by RiyaBhandari-2811** [khushi-purwar/WebDev-ProjectKart#127]
**Project title**
_Login Form  Project_

**Project Description**
_A project that allows you to fill the details and login to the website._

**Stack**:  
- [x] Html
- [x] CSS
- [x] Javascript
- [x] Reactjs

**Note**:
@khushi-purwar , As a **GSSOC-Contributor '22**  I would like to contribute through these issue if you give me the opportunity . If yes pls do comment so I can start working accordingly . Thank you :)

**Comment by Simran2337** [comment]
As a gssco'22 participant , I want to contribute in this from creation
Please allow me, Thankyou

**Comment by RiyaBhandari-2811** [comment]
@Simran2337  These is my issue i raise these issue , how would I assign it to you . I want to work on these issue that's why I raise it  .

**Comment by Simran2337** [comment]
Got it

**Comment by RiyaBhandari-2811** [comment]
@meinhoonharsh  what is Level3 ??

**Comment by khushi-purwar** [comment]
> @meinhoonharsh what is Level3 ??

Level3 means Hard. If you will add a new project in this repo according to the tech stack, then project will counted as level3

**Comment by RiyaBhandari-2811** [comment]
> > @meinhoonharsh what is Level3 ??
> 
> Level3 means Hard. If you will add a new project in this repo according to the tech stack, then project will counted as level3

So its good or bad , Level3 means project difficulty level ???

**Comment by meinhoonharsh** [comment]
There is nothing good or bad
All contribution are Good
It's just to categorize them into kind of contribution

**Comment by RiyaBhandari-2811** [comment]
> There is nothing good or bad All contribution are Good It's just to categorize them into kind of contribution

Ohh I see thanks mate 🙌🏻
