### ISSUE TITLE
Fluid Website.

### ISSUE THREAD

**Issue by Avik-creator** [khushi-purwar/WebDev-ProjectKart#1270]
**Project title**
It is a Fluid Website.

**Project Description**
It is a responsive fluid website made by Using HTML, CSS. 

**Stack**:  

- [x] Html
- [x] CSS

** Picture **:
<img width="575" alt="Screenshot 2022-05-06 at 4 23 38 PM" src="https://user-images.githubusercontent.com/77090462/167118718-ed6310c2-8e1a-419b-b32d-24c73b3244d6.png">

**Comment by Avik-creator** [comment]
@gurjeetsinghvirdee @khushi-purwar Please assign this issue to me.

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @Avik-creator

**Comment by Avik-creator** [comment]
Ok sir
