### ISSUE TITLE
Want to add a music kit

### ISSUE THREAD

**Issue by soumali28** [khushi-purwar/WebDev-ProjectKart#1274]
**Project title**
Music Kit
**Project Description**
This is a music kit comprising tabla, guitar and drum

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

![Music kit - Google Chrome 06-05-2022 19_36_29](https://user-images.githubusercontent.com/66300439/167149563-afdd840e-f2ca-4b91-a910-a84be54916b3.png)
![Music kit - Google Chrome 06-05-2022 19_36_36](https://user-images.githubusercontent.com/66300439/167149590-9dcbb4ab-2f08-46e7-aa88-96d89585ec1c.png)
![Music kit - Google Chrome 06-05-2022 19_36_44](https://user-images.githubusercontent.com/66300439/167149632-4bb1142b-2b64-4d9a-a279-8aa86bc240d6.png)

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @soumali28
