### ISSUE TITLE
Our Fitness

### ISSUE THREAD

**Issue by i-am-aisha** [khushi-purwar/WebDev-ProjectKart#1281]
**Project title**
I want to add a project of GYM website "OurFitnessCenter" .

**Project Description**
website will contain 4 sections home , services , about us and contact us and showing the plans and pricing details .

**Stack**: 

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by i-am-aisha** [comment]
@gurjeetsinghvirdee please assign

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee please assign

Assigned
