### ISSUE TITLE
Car Racing Game

### ISSUE THREAD

**Issue by AnIkeT126** [khushi-purwar/WebDev-ProjectKart#1282]
**Project title**

Car racing game

**Project Description**

Web app for car racing game

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee bhai assign

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee bhai assign

assigned
