### ISSUE TITLE
Find me!

### ISSUE THREAD

**Issue by AnIkeT126** [khushi-purwar/WebDev-ProjectKart#1283]
**Project title**

Find Me!

**Project Description**

A web app to find a word in a sequence of jumbled words.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by AnIkeT126** [comment]
@gurjeetsinghvirdee bhai assign

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee bhai assign

assigned
