### ISSUE TITLE
NLP Question Answering App

### ISSUE THREAD

**Issue by shreya024** [khushi-purwar/WebDev-ProjectKart#1293]
**Project title**
NLP Question Answering App

**Project Description**
The app can be used to build a system that can answer users’ questions in natural language.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript
- [x] ReactJS

**Comment by gurjeetsinghvirdee** [comment]
Assigned to u @shreya024
