### ISSUE TITLE
Real time face detection using webcam

### ISSUE THREAD

**Issue by YalfamIamShaon** [khushi-purwar/WebDev-ProjectKart#1295]
**Project title**
Real time face detection using webcam

**Project Description**
It will ask for your camera permission and will detect your face 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @YalfamIamShaon
