### ISSUE TITLE
Sling Shot Game

### ISSUE THREAD

**Issue by Avik-creator** [khushi-purwar/WebDev-ProjectKart#1299]
**Project title**
Sling Shot Game

**Project Description**
It is a sling shot game.

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Avik-creator** [comment]
@gurjeetsinghvirdee @meinhoonharsh please assign me this.

**Comment by gurjeetsinghvirdee** [comment]
Assigned
