### ISSUE TITLE
Email Extractor

### ISSUE THREAD

**Issue by AnIkeT126** [khushi-purwar/WebDev-ProjectKart#1306]
**Project title**

Email Extractor

**Project Description**

A web app to extract emails from a given texts. 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
-

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @AnIkeT126
