### ISSUE TITLE
Real Estate Website Design

### ISSUE THREAD

**Issue by Akshata-Gunapache** [khushi-purwar/WebDev-ProjectKart#1331]
**Project title**
Real Estate Website Design

**Project Description**
Responsive Real State Website Design Using HTML CSS & JavaScript

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by gurjeetsinghvirdee** [comment]
Assigned
