### ISSUE TITLE
Fix the Ui of website + Link all projects

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [khushi-purwar/WebDev-ProjectKart#1333]

**Comment by Avik-creator** [comment]
Can I do it?

**Comment by aaryahjolia** [comment]
Can I work on this ?
I will improve the heading to align it in center and will link all projects. (3 projects in a row)

**Comment by gurjeetsinghvirdee** [comment]
assigned to u @aaryahjolia

**Comment by aaryahjolia** [comment]
![image](https://user-images.githubusercontent.com/82600388/167271631-215d5983-0919-406c-91be-50caefbdf138.png)


@gurjeetsinghvirdee Any changes required ?

**Comment by gurjeetsinghvirdee** [comment]
> ![image](https://user-images.githubusercontent.com/82600388/167271631-215d5983-0919-406c-91be-50caefbdf138.png)
> 
> 
> @gurjeetsinghvirdee Any changes required ?

Have to link all project

**Comment by aaryahjolia** [comment]
Yes I've linked all of them. I was just asking about the UI. So should I make a PR ?
