### ISSUE TITLE
Typing Speed Test Website

### ISSUE THREAD

**Issue by rahulXbarnwal** [khushi-purwar/WebDev-ProjectKart#135]
**Project title**
Typing Speed Test Website

**Project Description**
This Website is made using HTML, CSS and JAVASCRIPT. This randomly generates some sentences and you have to type those sentences in the TextArea. On the basis of your typing, it will reflect your Typing Speed (words per min) and number of errors in the typed Sentence.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by rahulXbarnwal** [comment]
I am a GSSoC'22 participant. I really want to contribute in this issue. Please assign this issue to me @khushi-purwar

**Comment by aparna-bhatt** [comment]
Hey, I want to contribute to this issue. Can you explain a bit what I have to do?
