### ISSUE TITLE
Scramble Game

### ISSUE THREAD

**Issue by rravi1401** [khushi-purwar/WebDev-ProjectKart#137]
**Project title**
Scramble Game

**Project Description**
Scramble Game is a challenging vocabulary game . This game is designed with the help of  HTML,  CSS,  JAVASCRIPT . In this, we have to look at the word which randomly arrange by letters and identify the word. 
They must rearrange the given letters to form the meaningful right word.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

**Comment by rravi1401** [comment]
Hey, I'm gssoc22 participant,  I'd really want to contribute in this issue ,kindly assign this issue to me @khushi-purwar

**Comment by TG922** [comment]
I would like to work on this one too if no one working on it assign it to me
