### ISSUE TITLE
Drag and drop image website

### ISSUE THREAD

**Issue by Areebah03** [khushi-purwar/WebDev-ProjectKart#1371]
**Project title**
Drag and Drop

**Project Description**
In this website we can drag a picture and place it in different boxes. Please assign it to me @gurjeetsinghvirdee 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by gurjeetsinghvirdee** [comment]
Can't assign already 3 issues open first complete them

**Comment by Areebah03** [comment]
@gurjeetsinghvirdee I have complete the 3 issues that were assign to me and created pull request.
