### ISSUE TITLE
Plagiarism Checker App

### ISSUE THREAD

**Issue by shreya024** [khushi-purwar/WebDev-ProjectKart#1375]
**Project title**
Plagiarism Checker App

**Project Description**
An app to check plagiarism of a given text

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] ReactJS

**Comment by gurjeetsinghvirdee** [comment]
> /assign

`/assign` doesn't work

Assigned u @shreya024
