### ISSUE TITLE
Improve the UI of Stopwatch_App

### ISSUE THREAD

**Issue by Sparsh-kumar10** [khushi-purwar/WebDev-ProjectKart#138]
**Project name**
(Stopwatch_App)

**Project link**
(https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/18.Stopwatch_App)

**Improvements suggested**
(Imporve the UI and add laps in stopwatch)

I am a contributor at GSSoC'22

**Comment by BeginnerCoder21** [comment]
Can I work on the UI part? I am a contributor under GSSOC'22

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903
