### ISSUE TITLE
Drawing App using JS

### ISSUE THREAD

**Issue by chandu6111** [khushi-purwar/WebDev-ProjectKart#14]
**Project title**
Drawing App using JS

**Project Description**
The app would have a canvas for drawing and some additional buttons for increasing, decreasing the size, and changing the colour, clearing the screen etc. 

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by chandu6111** [comment]
@khushi-purwar could you please assign me this issue under ICC

**Comment by TechnicalAmanjeet** [comment]
what is this icc'21?

**Comment by khushi-purwar** [comment]
> what is this icc'21?

@TechnicalAmanjeet ICC stands for Infinite Clone Conspiracy, an open source program. You have created a PR also, as a participant of ICC.
