### ISSUE TITLE
Chess

### ISSUE THREAD

**Issue by Avik-creator** [khushi-purwar/WebDev-ProjectKart#1403]
**Project title**
Chess Game

**Project Description**
It will be a Chess Game

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Avik-creator** [comment]
@gurjeetsinghvirdee please assign me this

**Comment by Avik-creator** [comment]
@Mrjoy832

**Comment by Mrjoy832** [comment]
https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Chess_Game
already present...try some unique
