### ISSUE TITLE
Missile Game

### ISSUE THREAD

**Issue by Avik-creator** [khushi-purwar/WebDev-ProjectKart#1404]
**Project title**
Missile Game

**Project Description**
It will be a Missile Game

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [X] JavaScript
- [X] SVG

**Comment by Avik-creator** [comment]
@gurjeetsinghvirdee @Mrjoy832 please assign me this

**Comment by Mrjoy832** [comment]
> **Project title** Missile Game
> 
> **Project Description** It will be a Missile Game
> 
> **Stack**: And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.
> 
> * [x]  Html
> * [x]  CSS
> * [x]  JavaScript
> * [x]  SVG

add some reference images or explain how it works

**Comment by Avik-creator** [comment]
![IMG_20220509_165601.jpg](https://user-images.githubusercontent.com/77090462/167400585-74e8b895-2b12-439e-a70b-4628c71b3326.jpg)
It will be the look of the final project. It will be a game where we have to defend ourselves from asteroids. Coming towards us.

**Comment by Avik-creator** [comment]
@Mrjoy832
