### ISSUE TITLE
Fully responsive education website

### ISSUE THREAD

**Issue by Areebah03** [khushi-purwar/WebDev-ProjectKart#1407]
**Project title**
iEducate

**Project Description**
I have created a template for fully responsive education website. Please assign it to me @gurjeetsinghvirdee 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Areebah03** [comment]
@amyra98  Can you please assign it to me :)

**Comment by gurjeetsinghvirdee** [comment]
But you have to make a PR tomorrow bcoz you already created 3!!

**Comment by Areebah03** [comment]
Ok sure. Thank you :)
