### ISSUE TITLE
Adding Responsiveness into "Breakout Game" code

### ISSUE THREAD

**Issue by Mrjoy832** [khushi-purwar/WebDev-ProjectKart#1412]
**Project name**
Breakout Game

**Project link**
(https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Breakout_Game)

**Improvements suggested**
- The Code is not responsive, so I want to add responsiveness to this project

**Comment by gurjeetsinghvirdee** [comment]
@Mrjoy832 ye project exist ni krta ab kuch aur dhunde ya isse close krde

**Comment by Mrjoy832** [comment]
> @Mrjoy832 ye project exist ni krta ab kuch aur dhunde ya isse close krde

Okay 👌
