### ISSUE TITLE
changes in contact us form

### ISSUE THREAD

**Issue by Samikshyasahoo** [khushi-purwar/WebDev-ProjectKart#143]
**Project name**
contact us

**Project link**
file:///C:/Users/samikshya/Desktop/webdev/WebDev-ProjectKart/11.Contact_Us_Form/index.html

**Improvements suggested**
(can I improve the UI of contact form and add a successfully submitted page)
I'm a GSSoC'22 contributor.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
