### ISSUE TITLE
Neumorphism Power button

### ISSUE THREAD

**Issue by Ankitsingh2001** [khushi-purwar/WebDev-ProjectKart#145]
Hello mam, I am a frontend developer, I am much more confident in my development skill.

I am using only 
**HTML**
**CSS**
**JAVASCRIPT**   in my projects bt here I  done my  project only **HTML**   and   **CSS**.

**Comment by RajatBhaskare7** [comment]
can you assign me this also

**Comment by khushi-purwar** [comment]
> can you assign me this also
The issue is created by @Ankitsingh2001 , so he is assigned.
You can create any other issue
