### ISSUE TITLE
Flappy Bird Game

### ISSUE THREAD

**Issue by AnIkeT126** [khushi-purwar/WebDev-ProjectKart#1450]
**Project title**

Bird Fly Game

**Project Description**

Bird Fly Game

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by AnIkeT126** [comment]
assign @gurjeetsinghvirdee

**Comment by gurjeetsinghvirdee** [comment]
Isme aur flappy bird me kitna fark hai?

**Comment by AnIkeT126** [comment]
> Isme aur flappy bird me kitna fark hai?

Bhai same hai... Mujhe naam hi nhi yaad aa rha tha , issue banata waqt... Abhi change krta hu naam😂

**Comment by Mrjoy832** [comment]
Already a Flappy Bird is there with HTML,CSS,JS

**Comment by AnIkeT126** [comment]
> Already a Flappy Bird is there with HTML,CSS,JS https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Flappy%20Bird%20Game%20Using%20Javascript

Mine is entirely different, atleast look at it once, before closing

**Comment by Mrjoy832** [comment]
> > Already a Flappy Bird is there with HTML,CSS,JS https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Flappy%20Bird%20Game%20Using%20Javascript
> 
> Mine is entirely different, atleast look at it once, before closing

Kindly add some references images...by which I will judge yours ..You haven't added any images or description related Your issue

**Comment by AnIkeT126** [comment]
> > > Already a Flappy Bird is there with HTML,CSS,JS https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Flappy%20Bird%20Game%20Using%20Javascript
> > 
> > 
> > Mine is entirely different, atleast look at it once, before closing
> 
> Kindly add some references images...by which I will judge yours ..You haven't added any images or description related Your issue

i will send a pr in an hr, kindly check back then.

**Comment by Mrjoy832** [comment]
> > > > Already a Flappy Bird is there with HTML,CSS,JS https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Flappy%20Bird%20Game%20Using%20Javascript
> > > 
> > > 
> > > Mine is entirely different, atleast look at it once, before closing
> > 
> > 
> > Kindly add some references images...by which I will judge yours ..You haven't added any images or description related Your issue
> 
> i will send a pr in an hr, kindly check back then.

okayy either you can dm me on discord

**Comment by AnIkeT126** [comment]
> > > > > Already a Flappy Bird is there with HTML,CSS,JS https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/Flappy%20Bird%20Game%20Using%20Javascript
> > > > 
> > > > 
> > > > Mine is entirely different, atleast look at it once, before closing
> > > 
> > > 
> > > Kindly add some references images...by which I will judge yours ..You haven't added any images or description related Your issue
> > 
> > 
> > i will send a pr in an hr, kindly check back then.
> 
> okayy either you can dm me on discord

sure
