### ISSUE TITLE
Birthday Reminder App

### ISSUE THREAD

**Issue by shreya024** [khushi-purwar/WebDev-ProjectKart#1482]
**Project title**
Birthday Reminder App
**Project Description**
an app that reminds users about birthdays

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] ReactJS

**Comment by shreya024** [comment]
@gurjeetsinghvirdee Kindly assign

**Comment by gurjeetsinghvirdee** [comment]
Assigned @shreya024
