### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by SachinMittal1766** [khushi-purwar/WebDev-ProjectKart#1493]
**Project title**
Sudoku Solver

**Project Description**
I want to make a Sudoku Solver which will solve sudoku for the user.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by gurjeetsinghvirdee** [comment]
@SachinMittal1766 we already have this project
