### ISSUE TITLE
Build a Music Player

### ISSUE THREAD

**Issue by codingkush** [khushi-purwar/WebDev-ProjectKart#15]
**Project title**

Music Player

**Project Description**

Create a music player in our  browser and listen cool songs .This Music player uses a simple, compact size design. You get basic music player functions like the next, previous, and play/pause button. 

**Stack**:
[✔ ] Html
[ ✔] CSS
[ ✔] JavaScript

**Comment by codingkush** [comment]
@khushi-purwar could you please assign me this issue under ICC'21 ..

**Comment by TechnicalAmanjeet** [comment]
@khushi-purwar i also like to work on this project. please assign it to me as well under ICC'21.

**Comment by khushi-purwar** [comment]
@codingkush you can work on this issue.

**Comment by khushi-purwar** [comment]
> @khushi-purwar i also like to work on this project. please assign it to me as well under ICC'21.

@TechnicalAmanjeet you can create a new issue, I will assign it to you.

**Comment by TechnicalAmanjeet** [comment]
okay..
