### ISSUE TITLE
Get Your GitHub profile

### ISSUE THREAD

**Issue by Kumar-Ankit56** [khushi-purwar/WebDev-ProjectKart#1535]
**Project title**
Get Your Github profile

**Project Description**
### The idea behind this project
IT is based on simple functionality which is searched and gotten.

### How does it work
While loading the page you will have the container with some messages and a search box. In the search box, you just need to enter your git profile name. You will have it with your GitHub account.

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

for more details please refer to the attached images.
![Screenshot (188)](https://user-images.githubusercontent.com/73521123/167451819-3f45f03c-49a0-4378-843b-53f26d4b01b5.png)

https://user-images.githubusercontent.com/73521123/167451922-cfbaac1f-9f16-46a1-92b4-022f6b9dfe26.mp4

**Comment by Kumar-Ankit56** [comment]
@gurjeetsinghvirdee plz checkout this also

**Comment by Kumar-Ankit56** [comment]
@Mrjoy832 bhaiya plz checkout this also.

**Comment by Mrjoy832** [comment]
> @Mrjoy832 bhaiya plz checkout this also.

no pr created?
