### ISSUE TITLE
Form validation website

### ISSUE THREAD

**Issue by Areebah03** [khushi-purwar/WebDev-ProjectKart#1589]
**Project title**
Dragon Travel Desk

**Project Description**
This is a form validation website that validate a form according to username, email, phone number and shows error if not entered according to valid username, email and phone number. Please assign it to me.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by gurjeetsinghvirdee** [comment]
Already there
