### ISSUE TITLE
Add a News Website

### ISSUE THREAD

**Issue by Aritra777** [khushi-purwar/WebDev-ProjectKart#159]
**Project title**
News Website

**Project Description**
This is a News website using news API.

- [x] Html
- [x] CSS
- [x] JavaScript
Please assign me.

**Comment by Aritra777** [comment]
Please assign me @khushi-purwar 
The website will look like [This](https://aritra777.github.io/News-website/)

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by ronitrangwani** [comment]
I would like to work on this issue under GSSOC'22. Can you assign this to me?
