### ISSUE TITLE
Portfolio Website 

### ISSUE THREAD

**Issue by LovishMalhotra** [khushi-purwar/WebDev-ProjectKart#1602]
Project title
Portfolio Website

Project Description
It tells top tech skills of future

Stack 
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by LovishMalhotra** [comment]
Assign me this

**Comment by aachal28** [comment]
Assign me this
