### ISSUE TITLE
Fruit world

### ISSUE THREAD

**Issue by srinjoy-26** [khushi-purwar/WebDev-ProjectKart#1638]
**Project title**
Fruit world

**Project Description**
A completely responsive webpage related to fruits , veggies and all.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS

**Comment by Mrjoy832** [comment]
![image](https://user-images.githubusercontent.com/77873383/167910951-0d731e35-3c68-42df-b31e-32302978e650.png)

??

**Comment by srinjoy-26** [comment]
> ![image](https://user-images.githubusercontent.com/77873383/167910951-0d731e35-3c68-42df-b31e-32302978e650.png)
> 
> ??

done
