### ISSUE TITLE
Job portal website

### ISSUE THREAD

**Issue by jyothi-k-g** [khushi-purwar/WebDev-ProjectKart#1640]
**Project title**
Online job portal website

**Project Description**
This website provides all the details of the jobs that are available in different companies where the candidates view the details of the openings

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by mayank-del** [comment]
@jyothi-k-g  how did you added labels in your issues?
