### ISSUE TITLE
Create The Dice Game

### ISSUE THREAD

**Issue by DishaRawal** [khushi-purwar/WebDev-ProjectKart#169]
Hello @khushi-purwar,
I am Disha Rawal, a GSsoc'22 Participant.
I saw your existing project named "Dice Game". I would like to make and add the same game as per the conditions specified in the readme file. Kindly assign this project to me so I can start working on it.
Thanks & Regards,

**Comment by TG922** [comment]
I would like to work on it if it's not done yet
