### ISSUE TITLE
Add Palindrome Checker 

### ISSUE THREAD

**Issue by khushigupta123** [khushi-purwar/WebDev-ProjectKart#170]
**Project title**
Palindrome Checker

**Project Description**
This project helps in finding whether a string is palindrome or not. User needs to enter a string and press the check button, the result will be displayed on his screen. It contains some effects to make the project more creative like different colors for different results.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

I am a GSSOC 2022 participant,
Kindly assign this issue to me.

**Comment by bhavyapathak20** [comment]
@meinhoonharsh 
I would like to work on this issue.
My Skills in web development :

1)HTML
2)CSS
3)Bootstrap
4)Javascript
5)Jquery

Apart from these, I have experience in **c++** and **python** as well

My experience :
5+ months of experience in UI design.
Worked on Hands-on projects. My Github repo shows it

**Comment by riya200208** [comment]
I want to work on this issue. Can you please assign me?
