### ISSUE TITLE
Add favicon to the website

### ISSUE THREAD

**Issue by khushigupta123** [khushi-purwar/WebDev-ProjectKart#171]
**Project title**
Add favicon to the website

Hello @khushi-purwar 
Currently, there is no favicon on the website, I want to design and create a beautiful favicon for your website.

Benefits of a favicon
- make website more attractive
- give website individuality
- makes it easier for user to recognize the website tab quickly among other tabs

I am a GSSOC 2022 participant,
Kindly assign this issue to me.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by ronitrangwani** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by bhavyapathak20** [comment]
@meinhoonharsh 
I would like to work on this issue.
My Skills in web development :

1)HTML
2)CSS
3)Bootstrap
4)Javascript
5)Jquery

My experience :
5+ months of experience in UI design.
Worked on Hands-on projects. My Github repo shows it
