### ISSUE TITLE
Digital clock

### ISSUE THREAD

**Issue by jyothi-k-g** [khushi-purwar/WebDev-ProjectKart#172]
**Project title**
Digital clock using Javascript

- [x] Html
- [x] CSS
- [x] JavaScript
 please assign this issue to me @khushi-purwar I'm an participant of gssoc 2022

**Comment by bhavyapathak20** [comment]
@meinhoonharsh 
I would like to work on this issue.
My Skills in web development :

1)HTML
2)CSS
3)Bootstrap
4)Javascript
5)Jquery

My experience :
5+ months of experience in UI design.
Worked on Hands-on projects. My Github repo shows it

**Comment by suman-shah** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by meinhoonharsh** [comment]
@bhavyapathak20 @suman-shah 
This Issue was created by @jyothi-k-g 
You can create another Issue which I can assign you
