### ISSUE TITLE
Adding New Project of Arithmetic Calculator

### ISSUE THREAD

**Issue by TusharKesarwani** [khushi-purwar/WebDev-ProjectKart#1720]
**Project title**
Arithmetic Calculator

**Project Description**
Calculator doing arithmetic operations and also with memory functionaity.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by TusharKesarwani** [comment]
Please assign me this issue.

**Comment by gurjeetsinghvirdee** [comment]
#1703
