### ISSUE TITLE
Draggable Navigation Bar

### ISSUE THREAD

**Issue by dheerajrao20** [khushi-purwar/WebDev-ProjectKart#1721]
**Project title**
Draggable Navigation Bar

**Project Description**
As modern web dev requires more crazy things So we can add a movable navigation box menu that can be dragged throughout the webpage.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

**Comment by dheerajrao20** [comment]
@khushi-purwar  Kindly assign this issue to me.

**Comment by gurjeetsinghvirdee** [comment]
#1703
