### ISSUE TITLE
Add a Maze Game Online with varying levels of difficulty

### ISSUE THREAD

**Issue by Srishti2128** [khushi-purwar/WebDev-ProjectKart#175]
**Project title**
Maze Game

**Project Description**
The maze game works by presenting a maze in front of the user with a caterpillar that would like to feed on the cabbage but has to reach it through a maze. **The player has to navigate the caterpillar using the arrow buttons of the keyboard or using the mouse and help it reach the cabbage**. It **also works on phone screens perfectly** and the user can select the caterpillar and send it to desired location using hand touch. This game also has option to select from **various difficulty levels viz : Easy, Medium, Hard and Extreme** and with each increasing level, the user is presented with a more complex maze. Every single maze is different and unique. The images can be seen below

**Easy Level :**

![Screenshot 2022-03-04 151008](https://user-images.githubusercontent.com/90510806/156745017-907031d4-e80e-4b80-9e4f-1d206914bbb1.png)

**Medium Level :**

![Screenshot 2022-03-04 151025](https://user-images.githubusercontent.com/90510806/156745061-0371d0d2-2e01-4f5d-b1d9-5b1cc905dfeb.png)

**Hard Level :**

![Screenshot 2022-03-04 151041](https://user-images.githubusercontent.com/90510806/156745125-0535741b-0b11-46fb-ab10-ef70f65f1b06.png)

**Extreme Level :**

![Screenshot 2022-03-04 151056](https://user-images.githubusercontent.com/90510806/156745162-9dac7947-3077-4f12-8c54-7bc89049a463.png)

When the user successfully completes the right path, **the number of steps taken is also printed on the screen along with a congratulations message**

![Screenshot 2022-03-04 151123](https://user-images.githubusercontent.com/90510806/156745358-33cc62b1-d6be-4ec5-8bd5-761f045a606f.png)

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**The project is live at** : https://srishti2128.github.io/Maze-Game/
Feel free to explore the game.

I would like to add this project to the ProjectKart website.

**Kindly assign me this task** @khushi-purwar @meinhoonharsh so I can start working on it and make a pull request as soon as possible. I am a GSSOC'22 participant as a contributor and have added the Drum Kit online webapp to the site previously in #48 

Thank You !!

**Comment by rajaditya28** [comment]
> **Project title** Maze Game
> 
> **Project Description** The maze game works by presenting a maze in front of the user with a caterpillar that would like to feed on the cabbage but has to reach it through a maze. **The player has to navigate the caterpillar using the arrow buttons of the keyboard or using the mouse and help it reach the cabbage**. It **also works on phone screens perfectly** and the user can select the caterpillar and send it to desired location using hand touch. This game also has option to select from **various difficulty levels viz : Easy, Medium, Hard and Extreme** and with each increasing level, the user is presented with a more complex maze. Every single maze is different and unique. The images can be seen below
> 
> **Easy Level :**
> 
> ![Screenshot 2022-03-04 151008](https://user-images.githubusercontent.com/90510806/156745017-907031d4-e80e-4b80-9e4f-1d206914bbb1.png)
> 
> **Medium Level :**
> 
> ![Screenshot 2022-03-04 151025](https://user-images.githubusercontent.com/90510806/156745061-0371d0d2-2e01-4f5d-b1d9-5b1cc905dfeb.png)
> 
> **Hard Level :**
> 
> ![Screenshot 2022-03-04 151041](https://user-images.githubusercontent.com/90510806/156745125-0535741b-0b11-46fb-ab10-ef70f65f1b06.png)
> 
> **Extreme Level :**
> 
> ![Screenshot 2022-03-04 151056](https://user-images.githubusercontent.com/90510806/156745162-9dac7947-3077-4f12-8c54-7bc89049a463.png)
> 
> When the user successfully completes the right path, **the number of steps taken is also printed on the screen along with a congratulations message**
> 
> ![Screenshot 2022-03-04 151123](https://user-images.githubusercontent.com/90510806/156745358-33cc62b1-d6be-4ec5-8bd5-761f045a606f.png)
> 
> **Stack**:
> 
> * [x]  Html
> * [x]  CSS
> * [x]  JavaScript
> 
> **The project is live at** : https://srishti2128.github.io/Maze-Game/ Feel free to explore the game.
> 
> I would like to add this project to the ProjectKart website.
> 
> **Kindly assign me this task** @khushi-purwar so I can start working on it and make a pull request as soon as possible. I am a GSSOC'22 participant as a contributor and have added the Drum Kit online webapp to the site previously in #48
> 
> Thank You !!

@meinhoonharsh Kindly have a look and if you can assign the issue, I can start the work rn.

**Comment by Srishti2128** [comment]
> **Project title**
> Maze Game
> 
> **Project Description**
> The maze game works by presenting a maze in front of the user with a caterpillar that would like to feed on the cabbage but has to reach it through a maze. **The player has to navigate the caterpillar using the arrow buttons of the keyboard or using the mouse and help it reach the cabbage**. It **also works on phone screens perfectly** and the user can select the caterpillar and send it to desired location using hand touch. This game also has option to select from **various difficulty levels viz : Easy, Medium, Hard and Extreme** and with each increasing level, the user is presented with a more complex maze. Every single maze is different and unique. The images can be seen below
> 
> **Easy Level :**
> 
> ![Screenshot 2022-03-04 151008](https://user-images.githubusercontent.com/90510806/156745017-907031d4-e80e-4b80-9e4f-1d206914bbb1.png)
> 
> **Medium Level :**
> 
> ![Screenshot 2022-03-04 151025](https://user-images.githubusercontent.com/90510806/156745061-0371d0d2-2e01-4f5d-b1d9-5b1cc905dfeb.png)
> 
> **Hard Level :**
> 
> ![Screenshot 2022-03-04 151041](https://user-images.githubusercontent.com/90510806/156745125-0535741b-0b11-46fb-ab10-ef70f65f1b06.png)
> 
> **Extreme Level :**
> 
> ![Screenshot 2022-03-04 151056](https://user-images.githubusercontent.com/90510806/156745162-9dac7947-3077-4f12-8c54-7bc89049a463.png)
> 
> When the user successfully completes the right path, **the number of steps taken is also printed on the screen along with a congratulations message**
> 
> ![Screenshot 2022-03-04 151123](https://user-images.githubusercontent.com/90510806/156745358-33cc62b1-d6be-4ec5-8bd5-761f045a606f.png)
> 
> **Stack**:  
> 
> - [x] Html
> - [x] CSS
> - [x] JavaScript
> 
> **The project is live at** : https://srishti2128.github.io/Maze-Game/
> Feel free to explore the game.
> 
> I would like to add this project to the ProjectKart website.
> 
> **Kindly assign me this task** @khushi-purwar @meinhoonharsh so I can start working on it and make a pull request as soon as possible. I am a GSSOC'22 participant as a contributor and have added the Drum Kit online webapp to the site previously in #48 
> 
> Thank You !!

@meinhoonharsh kindly assign me this issue.

**Comment by meinhoonharsh** [comment]
@Srishti2128 you can work on this issue now

**Comment by Srishti2128** [comment]
> @Srishti2128 you can work on this issue now

Please add the GSSOC label to it . Thank you

**Comment by Srishti2128** [comment]
Thanks for assigning !

**Comment by Srishti2128** [comment]
The PR is made #188 . Kindly review and merge it.
Thank You !
