### ISSUE TITLE
Random Jokes

### ISSUE THREAD

**Issue by Pranav-Vyas** [khushi-purwar/WebDev-ProjectKart#176]
**Project title**
Random Jokes

**Project Description**
In this project user will click the button "Get Joke" and will get a new joke every time.

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Pranav-Vyas** [comment]
Hey, I'm a GSSoC 22 participant. I would like to contribute to this issue. Kindly assign it to me. @khushi-purwar

**Comment by meinhoonharsh** [comment]
@Pranav-Vyas assigned to you

**Comment by bhavyapathak20** [comment]
@meinhoonharsh  I would like to work on this issue
My Skills in web development :

1)HTML
2)CSS
3)Bootstrap
4)Javascript
5)Jquery

My experience :
5+ months of experience in UI design.
Worked on Hands-on projects. My Github repo shows it
