### ISSUE TITLE
Reaction Tester Game

### ISSUE THREAD

**Issue by arzitmahajan** [khushi-purwar/WebDev-ProjectKart#178]
**Project title**
(Reaction Tester Game)

**Project Description**
(Reaction Tester  Game That counts how fast you click on the element that pop up at random place on screen)

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

**Comment by arzitmahajan** [comment]
Please assign me this task

**Comment by arzitmahajan** [comment]
why it is not merged?

**Comment by khushi-purwar** [comment]
> why it is not merged?

It is merged, then it is closed

**Comment by arzitmahajan** [comment]
oh okay sorry I am new to open source still learning how everything works

**Comment by khushi-purwar** [comment]
> oh okay sorry I am new to open source still learning how everything works

No problem. You can ask anytime.

**Comment by arzitmahajan** [comment]
Thank you 😊
