### ISSUE TITLE
Add backend code to the contact us form.(GSSOC'22 contributor)

### ISSUE THREAD

**Issue by Rp-Shamita** [khushi-purwar/WebDev-ProjectKart#182]
**Project name**
Contact_Us_Form

**Project link**
https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/11.Contact_Us_Form

**Improvements suggested**
As the contact us from is not responsive and it is only the front end present will add the backend part of it by storing the details in MySQL database using PHP.

**Comment by riya200208** [comment]
I want to work on this issue. Please assign me.

**Comment by Rp-Shamita** [comment]
I brought out this issue cause i’m confident in this area. I want to work on it as well. Sent from Mail for Windows From: Riya DasSent: 04 March 2022 20:19To: khushi-purwar/WebDev-ProjectKartCc: R P Shamita; AuthorSubject: Re: [khushi-purwar/WebDev-ProjectKart] Add backend code to the contact us form.(GSSOC'22 contributor) (Issue #182) I want to work on this issue. Please assign me.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
