### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by Atif0604** [khushi-purwar/WebDev-ProjectKart#196]
**Project title**
Snake Game
**Project Description**
Want to Add Snake Game

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

**Comment by TG922** [comment]
I can make PR regarding this within 1 day, as I have already gone through this project earlier.
