### ISSUE TITLE
Text to Speech Convertor 

### ISSUE THREAD

**Issue by Atharv-110** [khushi-purwar/WebDev-ProjectKart#216]
**Project title**
Text to Speech Convertor 

**Project Description**
This convertor will convert everything you type in the text area into desired language user want to listen.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

#### Consider it under GSSoC'22

**Comment by TG922** [comment]
@amyra98 I would like to work on it it's been a month

**Comment by Atharv-110** [comment]
Raising PR in few hours as my mid semester examinations were going on

**Comment by TG922** [comment]
Ok @Atharv-110 I can work on other issues
