### ISSUE TITLE
GitHub Profiles

### ISSUE THREAD

**Issue by shivam123-dev** [khushi-purwar/WebDev-ProjectKart#218]
**Project title**
GitHub Profiles
**Project Description**
Want to Add GitHub Profiles Search App

Stack:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by shivam123-dev** [comment]
I am GSSOC'22 contributor. @khushi-purwar and @meinhoonharsh kindly assign me this issue

**Comment by meinhoonharsh** [comment]
@shivam123-dev Assigned to You
