### ISSUE TITLE
Editing the home page

### ISSUE THREAD

**Issue by naugsss** [khushi-purwar/WebDev-ProjectKart#225]
According to me, the home page doesn't looks attractive at all.. So we need to change the CSS of the home page. 
The site will look much better if every link can be arranged in the form of tile with a bit description and a pic of the same. 

![Screenshot_2022-03-06-23-37-39-942_com android chrome](https://user-images.githubusercontent.com/89718207/156936159-80d9c5f3-86f8-4657-85d6-4a96e3a83e5a.jpg)

Here you can see each course has its own description and an image added to it... So we can do the same to the home page

**Comment by Aniket1026** [comment]
I'd really love to work on this issue and make the home page interface better for the user.

**Comment by naugsss** [comment]
@Aniket1026 we can work together in this issue if you want to pair up
