### ISSUE TITLE
Flappy bird game

### ISSUE THREAD

**Issue by MarkL50** [khushi-purwar/WebDev-ProjectKart#243]
**Project title**
Flappy bird game

**Project Description**
Flappy bird game using javascript to kill boredom and have some fun while you are free.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by TG922** [comment]
I would like to work on this issue it's been 28 days please assign it to me, if it is not done
