### ISSUE TITLE
PingPong_ScoreKeeper

### ISSUE THREAD

**Issue by sm-sourabh** [khushi-purwar/WebDev-ProjectKart#251]
Score Keeper 

**Project Description**
This project aims to keep a score of two players playing ping pong (Can be used for any other game as well). Reset button nullifies the score to zero. Number of rounds can be alloted in the start of the game.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

It will look something like this :
![111](https://user-images.githubusercontent.com/76443555/157201652-e373bf14-6af5-4b85-aa10-57aea7f724be.PNG)

**Comment by sm-sourabh** [comment]
hi @khushi-purwar ,Please asssigned me with this project. I will be making the pull request within 3 days of alloted time. #GSSOC22

**Comment by BabyElias** [comment]
I think someone else has already created and assigned himself this issue(Issue #250)  just before you  , so they aren't assigning you .Nonetheless if you think your issue is difft from #250 , you can surely self-assign it to yourself by typing /assign in the comment box here.

**Comment by khushi-purwar** [comment]
Yes @sm-sourabh , @BabyElias is right. The same issue is already assigned. You can create another issue.
