### ISSUE TITLE
Image of Project Maintainer in readme.md is broken

### ISSUE THREAD

**Issue by BabyElias** [khushi-purwar/WebDev-ProjectKart#260]
The image of Project Maintainer in readme.md is broken and clicking on its source code in readme.md returns an access denied error.

**Comment by BabyElias** [comment]
https://media-exp1.licdn.com/dms/image/C5603AQFQjgQVGH77fQ/profile-displayphoto-shrink_400_400/0/1621153995462?e=1646265600&v=beta&t=rBye2Q3S0h5bXjy49WDcKlvmzVPvxs5wFuLERK_vsRg

This link as mentioned in the readme shows access denied. Any other link to the image intended to be there?

**Comment by khushi-purwar** [comment]
You can create any other issue as image of project maintainer is clearly visible in the readme file. I am closing this issue.
