### ISSUE TITLE
Customer Review Webapp

### ISSUE THREAD

**Issue by XZANATOL** [khushi-purwar/WebDev-ProjectKart#275]
**Project title**
Customer Review Webapp

**Project Description**
A Flask based app that provides the user with a form to fill a feedback about a product and saves it into a csv file to be listed in a simple webpage

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] Python (Gonna include a readme of the required steps to run the app locally)

Issue created under GSSoC'22 contributions.

**Comment by XZANATOL** [comment]
@khushi-purwar are such apps applicable in the repo?

**Comment by khushi-purwar** [comment]
Issue is not valid for this repo.
This repo uses HTML , CSS , JS and NodeJS only.
We cannot add your python project.

**Comment by khushi-purwar** [comment]
I am closing this issue.
