### ISSUE TITLE
Fingerprint scanning animation

### ISSUE THREAD

**Issue by srinjoy-26** [khushi-purwar/WebDev-ProjectKart#277]
Project description:-
Made using HTML and CSS animations.
Here is how it looks - 
<img width="438" alt="scan" src="https://user-images.githubusercontent.com/91176055/157718256-814ca132-0c5f-49d2-9a12-97a11b1184e5.png">

please /assign me.

**Comment by SandeepShekhawat8778** [comment]
okay bro you can go with this task @srinjoy-26

**Comment by srinjoy-26** [comment]
how can get assigned bro
