### ISSUE TITLE
Lights out Game

### ISSUE THREAD

**Issue by AnIkeT126** [khushi-purwar/WebDev-ProjectKart#280]
**Project title**

Lights Out Game

**Project Description**

This is a complex game designed on 5 * 5, 6 * 6 & 7 * 7 boards.
The basic idea behind the game is that initially some squares will be of color X and others will be of color Y, where X denotes light on and Y denotes light off.
You have to turn the light of all squares off or make them of color Y so as to say by flipping the tile, but the catch is that once you flip the tile to change its colo/light mod, not only its color change but the color of its adjacent neighbors in the X & Y direction also changes, so the complexity increases as you keep flipping the tile, neighbors also get changed. 
In the end, player wins if all tiles are turned off, i.e. all neighbors of all tiles are turned off. 

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

**Comment by AnIkeT126** [comment]
@khushi-purwar can you please assign a level label to this?

**Comment by AnIkeT126** [comment]
@khushi-purwar can you please assign a level label to this?

**Comment by TG922** [comment]
I would like to work on this one
