### ISSUE TITLE
Adding Movie Recommendation App

### ISSUE THREAD

**Issue by Mohasin-Haque** [khushi-purwar/WebDev-ProjectKart#29]
**Movie Recommendation App**

**Project Description**
This project suggest you movies to watch. This app have many genres also. Just dive in and watch a good movie of your choice.

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Mohasin-Haque** [comment]
I want to work on this issue. Please assign me this issue so that I can work on it.

**Comment by khushi-purwar** [comment]
This is issue is for ICC'21?

**Comment by Mohasin-Haque** [comment]
Sorry but ICC is over, so i am doing this as an open source contribution

**Comment by khushi-purwar** [comment]
> Sorry but ICC is over, so i am doing this as an open source contribution

Ok.
