### ISSUE TITLE
Build a small Quiz App

### ISSUE THREAD

**Issue by khushi-purwar** [khushi-purwar/WebDev-ProjectKart#3]
**Project title**
Quiz Application

**Project Description**
Create a JavaScript Quiz Game and at last show the result to the users.

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by TechnicalAmanjeet** [comment]
hay I want to work on this project. if no-one is working on this then assign it to me.

**Comment by khushi-purwar** [comment]
> hay I want to work on this project. if no-one is working on this then assign it to me.

Now you can work on it, I have assigned this issue to you.

**Comment by TechnicalAmanjeet** [comment]
okay.
