### ISSUE TITLE
URL Shortening page

### ISSUE THREAD

**Issue by Karnika06** [khushi-purwar/WebDev-ProjectKart#31]
**Project title**
URL Shortening page

**Project Description**
To integrate with the shrtcode API to create shortened URLs and display them like in the designs using React framework.

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Karnika06** [comment]
Hey @khushi-purwar, please assign this issue to me..!!

**Comment by varisha-025** [comment]
Hello @khushi-purwar, I am a participant in GSSoc 2022 and I would like to work on this issue.

**Comment by khushi-purwar** [comment]
> Hello @khushi-purwar, I am a participant in GSSoc 2022 and I would like to work on this issue.

Hello, @varisha-025, the issue cannot be assigned before 1st march as the coding period starts from 1 march.

**Comment by Bhawna147** [comment]
@khushi-purwar I want to work on this issue under GSSOC'22. Please assign this to me.

**Comment by khushi-purwar** [comment]
@varisha-025 you can start working on this issue.

**Comment by varisha-025** [comment]
Sure mam

**Comment by varisha-025** [comment]
@khushi-purwar I need to use Node.js for this task. Can I?
