### ISSUE TITLE
Guess My Number

### ISSUE THREAD

**Issue by rahul123gautam** [khushi-purwar/WebDev-ProjectKart#311]
**Project title**
(Write project title over here)

**Project Description**
(Describe the project over here)

**Project title**
Guess My Number

**Project Description**
It is a quite nice game . computer generate the number and user need to guess the generated number.

**Stack**:  

- [] Html
- [] CSS
- [] JavaScript
-
![Screenshot (116)](https://user-images.githubusercontent.com/93531189/158289286-dfc4fc93-e8f8-4dae-9de8-ea6b3d6009f5.png)

**Comment by rahul123gautam** [comment]
assign

**Comment by TG922** [comment]
I would like to work on this issue if it is not done ye @khushi-purwar
