### ISSUE TITLE
I want to add a simple react project which is a clone of Trello/Kanban board

### ISSUE THREAD

**Issue by TANYA-CHAN** [khushi-purwar/WebDev-ProjectKart#316]
**Project title**
A simple Trello clone using react dnd

**Project Description**
A Kanban board using React.js and react-dnd lib.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x ] Html
- [x ] CSS
- [x ] JavaScript
- [x ] ReactJS

**Comment by TANYA-CHAN** [comment]
I have created a ew pull request but idk why it is not showing the files changed again, I followed the same instructions on the main repo. I'll try once again.

**Comment by gurjeetsinghvirdee** [comment]
@TANYA-CHAN are you making a new PR?

**Comment by TANYA-CHAN** [comment]
I did make a new PR as it directed me to do so.
