### ISSUE TITLE
Enhancement in Code and New Features

### ISSUE THREAD

**Issue by Rahulbaran** [khushi-purwar/WebDev-ProjectKart#33]
**Project name**
Random Gradient Color

**Project link**
[link](https://khushi-purwar.github.io/WebDev-ProjectKart/21.Random_grediant_color/)

**Improvements suggested**
1. Providing `100vh` height to body tag
2.  Using a function to generate random values of **x, y, z & a** in JS will make the code **DRY**.
3. Providing a **Copy** button to copy the generated gradient to clipboard

**Comment by Surajkarle77** [comment]
I would like to work over this, please assign it to me
I will make click me button more attractive (i.e add shadow, some cool hover effect) and also copy button for copy the gradient
and many more..

**Comment by khushi-purwar** [comment]
> I would like to work over this, please assign it to me I will make click me button more attractive (i.e add shadow, some cool hover effect) and also copy button for copy the gradient and many more..

@Surajkarle77 , I will start assigning issue from 1st march as coding phase will starts from 1st march.

**Comment by khushi-purwar** [comment]
@Surajkarle77 you can start working on this issue.
