### ISSUE TITLE
 Love Calculator

### ISSUE THREAD

**Issue by iamrahulmahato** [khushi-purwar/WebDev-ProjectKart#342]
**Project title**
 Love Calculator

**Project Description**
It will be a love calculator which will calculate how much your crush likes you

**Stack**:  

- [] Html
- [] CSS
- [] JavaScript

**Comment by iamrahulmahato** [comment]
@khushi-purwar @meinhoonharsh @amyra98 please assign me this issue!!!

**Comment by meinhoonharsh** [comment]
Hey @iamrahulmahato 
Please read the comment by GitHub Actions Bot carefully

**Comment by iamrahulmahato** [comment]
@meinhoonharsh ok  i have to self assigns
