### ISSUE TITLE
Weather Application is not responsive

### ISSUE THREAD

**Issue by Sunil4510** [khushi-purwar/WebDev-ProjectKart#35]
**Project name**
(Weather Application)

**Project link**
(https://khushi-purwar.github.io/WebDev-ProjectKart/15.Weather_Application/)

**Improvements suggested**
(use media queries for different devices make it responsive and super clean)

Happy Coding!

**Comment by Ajoe12** [comment]
Please assign it to me I will make it reponsive

**Comment by khushi-purwar** [comment]
> Please assign it to me I will make it reponsive

@Ajoe12 , before 1st march, no issue can be assigned to anyone as coding phase will starts from 1st march.

**Comment by Pranavv213** [comment]
Please assign to me. I can use things like media queries, flexbox etc to make it responsive . I am a GSSoC' 22 participant and want to contribute to it

**Comment by 1ananya3** [comment]
Is anyone already working on this? If not Then please assign it to me .I can work on this.

**Comment by Ajoe12** [comment]
Please assign me this issue so that I can start working on it, I had worked with media queries on my various projects and will make it responsive, I want to contribute to this project.

**Comment by khushi-purwar** [comment]
@Sunil4510 you can start working on this issue.
