### ISSUE TITLE
Portfolio Website

### ISSUE THREAD

**Issue by Deep-anjali01** [khushi-purwar/WebDev-ProjectKart#37]
**Project title**
Portfolio website

**Project Description**
I will make my portfolio website using all the three stacks mentioned below. It will have all my contact, details , work history , education, achievements etc...

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@Deep-anjali01 you can start working on this issue

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by khushi-purwar** [comment]
> I want to work on this under GSSOC2022. Can you assign it to me.

Yes you can work on it. If you know reactjs, then you can add that also

**Comment by Abhilasha-Jairath** [comment]
> > I want to work on this under GSSOC2022. Can you assign it to me.
> 
> Yes you can work on it. If you know reactjs, then you can add that also

Yea I know three of them well !!

**Comment by ronitrangwani** [comment]
I would like to work on this issue under GSSOC 2022. Can you assign this to me?

**Comment by pushpanjali-10** [comment]
Hi, I am a GSSOC Contributor and I would like to work on this issue. please assign this issue to me.
