### ISSUE TITLE
Ping Pong Ball Score Keeper

### ISSUE THREAD

**Issue by yellowberard** [khushi-purwar/WebDev-ProjectKart#379]
**Project title**
Ping Pong Ball Score Keeper

**Project Description**
In this project user can keep score of their game and in the end winner is also declared.

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
This issue is already created by someone. Please raise any other issue. I am closing this issue.
