### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by SamarthKadam** [khushi-purwar/WebDev-ProjectKart#385]
**Project title**
Groovvy Music Player

**Project Description**
Here I  built an Music Player which has currently got 4 songs using js You can visit the webiste hosted in https://groovvy.netlify.app/.
Can you please /assign me this
**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript
- [] ReactJS

**Comment by SamarthKadam** [comment]
Can I make an PR Khushi ?

**Comment by khushi-purwar** [comment]
> Can I make an PR Khushi ?

Yes, you can.
