### ISSUE TITLE
I want to add a react project which contains top 5 Coding platforms. 

### ISSUE THREAD

**Issue by BhoomikaSahu** [khushi-purwar/WebDev-ProjectKart#39]
**Coding Platforms**
(Top 5 Coding Platforms)

**Project Description**
(It is frontend project which made in ReactJS. It shows to users top 5 coding platforms. I will extend this project and add more functionality like will  add all recourses for CP and learning development for beginners. )

**Stack**:
[ ] Html
[ ] CSS
[ ] ReactJS
![WhatsApp Image 2022-02-10 at 7 28 33 PM](https://user-images.githubusercontent.com/70888716/155889718-5d906a22-c5b3-46d9-b2ef-fe20f3d5492a.jpeg)

**Comment by khushi-purwar** [comment]
@BhoomikaSahu are you a contributor in GSSoC'22?

**Comment by BhoomikaSahu** [comment]
> 

Yes I am contributor in GSSoC'22

**Comment by khushi-purwar** [comment]
> > 
> 
> Yes I am contributor in GSSoC'22

OK Bhoomika, I will start assigning the issue from 1st march, as contribution period will start from 1st onwards.

**Comment by BhoomikaSahu** [comment]
> > > 
> > 
> > 
> > Yes I am contributor in GSSoC'22
> 
> OK Bhoomika, I will start assigning the issue from 1st march, as contribution period will start from 1st onwards.

> Okay Thank You, I am super excited for it :)

**Comment by BhoomikaSahu** [comment]
Okay Thank You, I am super excited for it :)

**Comment by khushi-purwar** [comment]
@BhoomikaSahu you can start working on this issue.

**Comment by BhoomikaSahu** [comment]
@khushi-purwar Okay Thank You, If I'll need your help, Where I will ping you?

**Comment by meinhoonharsh** [comment]
> @khushi-purwar Okay Thank You, If I'll need your help, Where I will ping you?

@BhoomikaSahu You can ask at Discord Server of Gssoc'22
