### ISSUE TITLE
Contact Us Form

### ISSUE THREAD

**Issue by khushi-purwar** [khushi-purwar/WebDev-ProjectKart#4]
**Project title**
Contact us Form

**Project Description**
Create a responsive contact us form using HTML & CSS. 

**Stack**:
- [x] Html
- [x] CSS

**Comment by sarazm2000** [comment]
Hi @khushi-purwar , Can I work on this issue?

**Comment by khushi-purwar** [comment]
> Hi @khushi-purwar , Can I work on this issue?

Yes.
