### ISSUE TITLE
Changing UI of index.html page

### ISSUE THREAD

**Issue by sanket95droid** [khushi-purwar/WebDev-ProjectKart#40]
Can I enhance the landing page (index.html) with row card stacking and other CSS styles?

**Comment by khushi-purwar** [comment]
Yes you can. But I will start assigning from tomorrow.

**Comment by khushi-purwar** [comment]
@sanket95droid you can start working on this issue.

**Comment by sanket95droid** [comment]
OR
I can directly make the card layout for each project (h1) in index.html and link it with CSS, without creating any scripts.

**Comment by Prajwal-ctrl** [comment]
Hii @khushi-purwar  i am not able to push to my branch its giving 403 error
