### ISSUE TITLE
Add Google Search Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [khushi-purwar/WebDev-ProjectKart#403]
**Project title**
Google Search Engine Clone

**Project Description**
Google Search Engine Clone using React Js with the help of Redux and Google Context API , it works like a real Google search engine if you search something it will give you all results 

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS
- [x] Node JS
- [x] Redux

**Comment by sampavaranasi** [comment]
@khushi-purwar https://github.com/surajm-333/Ace-The-FrontEnd/issues/23
