### ISSUE TITLE
Newsletter Signup Page

### ISSUE THREAD

**Issue by uhini0201** [khushi-purwar/WebDev-ProjectKart#41]
**Project title**
Newsletter Signup

**Project Description**
I want  to add a newsletter signup page which has api call with a newsletter.
@khushi-purwar If you find this to be required Please assign me this issue, I am a GSSOC'22 contributor.

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript
- [x] Node.js

**Comment by khushi-purwar** [comment]
@uhini0201 , I will start assigning from tomorrow. 
This repo is only for HTML, CSS , JS & ReactJS so that it can deploy on github pages as well.
I did not include the NodeJS. But if you wish you can add.

**Comment by uhini0201** [comment]
> @uhini0201 , I will start assigning from tomorrow. This repo is only for HTML, CSS , JS & ReactJS so that it can deploy on github pages as well. I did not include the NodeJS. But if you wish you can add.

So Will i be able to contribute here???? It will work here if i provide the project link after deployment i suppose

**Comment by uhini0201** [comment]
@khushi-purwar  So will you assign me this issue???

**Comment by khushi-purwar** [comment]
> @khushi-purwar So will you assign me this issue???

Yes, I will assign it to you but on 1st march. As the contribution period starts from there

**Comment by uhini0201** [comment]
Okk thanks a lot @khushi-purwar

**Comment by khushi-purwar** [comment]
@uhini0201 you can start working on this issue.
