### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by khushi-purwar** [khushi-purwar/WebDev-ProjectKart#44]
**Project title**
Image Gallery

**Project Description**
In this project, integrate Tailwind CSS with ReactJS and use the pixabay API to build an image gallery

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] ReactJS
- [x] Tailwind CSS

**Comment by Puja-Saraf** [comment]
claim
