### ISSUE TITLE
Add 2048 game 

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [khushi-purwar/WebDev-ProjectKart#444]
**Project title**
2048 Game Clone

**Project Description**
2048 Game in React Js you can play this game in different sizes like classic, big, huge and this game was mobile responsive 

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

**Comment by sampavaranasi** [comment]
@khushi-purwar https://github.com/abhijeet007rocks8/Dev-Scripts/issues/241
