### ISSUE TITLE
Add animated flip card using reactjs

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [khushi-purwar/WebDev-ProjectKart#446]
**Project title**
Animated flip card

**Project Description**
I want to add animated flip card using reactjs that would be userfriendly.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [] Html
- [] CSS
- [] JavaScript
- [] ReactJS

**Comment by Tanuj-rai** [comment]
can you please assign me this issue?

**Comment by gurjeetsinghvirdee** [comment]
@Tanuj-rai assigned to u

**Comment by gurjeetsinghvirdee** [comment]
@Tanuj-rai are you working on this PR or I close this?
