### ISSUE TITLE
[BUG IN ] Readme.md file

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [khushi-purwar/WebDev-ProjectKart#45]
Hii there , Greeting's of the day 
Readme is one of the most important part of the repository  which consist of the guidence and flow of conduct . .and if it conatins eroor's then it gave a bad impact ...on organisation

As ur readme conatain's the grammaratical error .. Please asisgn this issue to me so that i can make this correct and grammatical good.
Consider this issue under the   ....
### GSSOC'22
Thank's :crossed_fingers:

**Comment by khushi-purwar** [comment]
Nice issue. I will assign it to you from tomorrow, as contribution period will starts from tomorrow.

**Comment by khushi-purwar** [comment]
@Vikash-8090-Yadav you can work on this issue.
