### ISSUE TITLE
Create BBC News Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [khushi-purwar/WebDev-ProjectKart#457]
**Project title**
Create a website clone for BBC News

**Project Description**
This is issue would create a clone for BBC News using HTML, CSS and JS.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [x] JavaScript
- [ ] ReactJS

**Comment by Kumar-laxmi** [comment]
@san-droid371 Hey I think you assigned it to yourself by mistake

**Comment by san-droid371** [comment]
> @san-droid371 Hey I think you assigned it to yourself by mistake

no, I want to work on this.

**Comment by Kumar-laxmi** [comment]
@khushi-purwar Please resolve this issue

**Comment by khushi-purwar** [comment]
You have to assign the issue yourself by writing the /assign. @Kumar-laxmi you have created the issue 3 days ago. But you have not assigned it.. it is mentioned in the message.  @san-droid371  assigned it. Now @san-droid371 will work on it. @Kumar-laxmi you can create another issue.
