### ISSUE TITLE
Add a new project  Sudoku-Solver-Game

### ISSUE THREAD

**Issue by kaustav202** [khushi-purwar/WebDev-ProjectKart#46]
**Project title**

Sudoku Solver Game

**Project Description**

This is a digital sudoku solver game with points tally and countdown timer.
It is made using vanilla js , html and css

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

![sudoku](https://user-images.githubusercontent.com/89788120/155985336-9fbcbf38-c1fb-47dc-92e9-b6475a32a58b.png)

**Comment by kaustav202** [comment]
I am gssoc22 contributor.
Can you assign me this task @khushi-purwar

**Comment by khushi-purwar** [comment]
> I am gssoc22 contributor. Can you assign me this task @khushi-purwar

It is a good project, I will start assigning from tomorrow.

**Comment by kaustav202** [comment]
> > I am gssoc22 contributor. Can you assign me this task @khushi-purwar
> 
> It is a good project, I will start assigning from tomorrow.

Sure ..look forward to it.

**Comment by kaustav202** [comment]
The project's been done and awaiting pr @khushi-purwar
