### ISSUE TITLE
Adding Quiz Game

### ISSUE THREAD

**Issue by AmolShelke2** [khushi-purwar/WebDev-ProjectKart#49]
**Project title**
(Quiz Game for Developers)

**MySelf**
I'm a GSSOC 022 participant.

**Project Description**
(It is a very simple quiz type game where it will be a question and there will be 4 multiple options for the user to select the answer if the answer will be correct then the user can be able to go on to the next question, for now, it has only four questions but the user can add their own questions and answers to the project🙂)

I'm attaching the DEMO please go through the Issue and I hope that you will assign me the issue to work on.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
![192 168 187 73_5501_QuizGame_index html](https://user-images.githubusercontent.com/95171638/156026339-fa6e62c0-3487-46d4-8577-ca0adc192963.png)

**Comment by khushi-purwar** [comment]
You can work on it!
