### ISSUE TITLE
File Upload using JS

### ISSUE THREAD

**Issue by khushi-purwar** [khushi-purwar/WebDev-ProjectKart#5]
**Project title**
File Upload 

**Project Description**
Add two options: Either by drag or drop or by browse
Upload the file by drag and drop feature or by using browse  button.

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

Similar to this,
<img width="466" alt="image" src="https://user-images.githubusercontent.com/52875298/146633291-e8587f03-690e-458e-b697-75d9740d9413.png">

**Comment by abaran803** [comment]
Hi @khushi-purwar , I want to work on this issue

**Comment by abaran803** [comment]
> > Hi @khushi-purwar , I want to work on this issue
> 
> Ok @abaran803. Kindly follow the project structure.

Not getting how to do it. Where to upload a file? Like if we want to get the current amount of an uploaded file, we need to use AJAX, fetch API or others, but all of these require a URL, where the file will be uploaded. I google about it a lot but found no solution.

**Comment by khushi-purwar** [comment]
> > > Hi @khushi-purwar , I want to work on this issue
> > 
> > 
> > Ok @abaran803. Kindly follow the project structure.
> 
> Not getting how to do it. Where to upload a file? Like if we want to get the current amount of an uploaded file, we need to use AJAX, fetch API or others, but all of these require a URL, where the file will be uploaded. I google about it a lot but found no solution.

@abaran803  Please DM me on discord. I will provide the materials regarding the topic.

**Comment by abaran803** [comment]
> > > > Hi @khushi-purwar , I want to work on this issue
> > > 
> > > 
> > > Ok @abaran803. Kindly follow the project structure.
> > 
> > 
> > Not getting how to do it. Where to upload a file? Like if we want to get the current amount of an uploaded file, we need to use AJAX, fetch API or others, but all of these require a URL, where the file will be uploaded. I google about it a lot but found no solution.
> 
> @abaran803 Please DM me on discord. I will provide the materials regarding the topic.

@khushi-purwar ok

**Comment by khushi-purwar** [comment]
@abaran803 have you completed this task?

**Comment by abaran803** [comment]
> @abaran803 have you completed this task?

Sorry @khushi-purwar, due to my ongoing semester exams, I am not able to complete them.

**Comment by khushi-purwar** [comment]
> > @abaran803 have you completed this task?
> 
> Sorry @khushi-purwar, due to my ongoing semester exams, I am not able to complete them.

Okay, no problem.

**Comment by sm-sourabh** [comment]
hello @khushi-purwar ,I want to attend this issue under GSSOC . Can you help me out with theprocess ?

**Comment by varisha-025** [comment]
hello @khushi-purwar, I want to work on this issue under GSSOC. Can you please assign me this?

**Comment by khushi-purwar** [comment]
> hello @khushi-purwar, I want to work on this issue under GSSOC. Can you please assign me this?

Hello, @varisha-025, the issue cannot be assigned before 1st march as the coding period starts from 1 march.

**Comment by abaran803** [comment]
@sm-sourabh Is this project available in GSSOC, can you tell me about how you get into this program?

**Comment by abaran803** [comment]
> @sm-sourabh Is this project available in GSSOC, can you tell me about how you get into this program?

@sm-sourabh Also, what's your linkedin profile?

**Comment by varisha-025** [comment]
hello @khushi-purwar, I want to work on this issue under GSSOC. Can you please assign me this?

**Comment by khushi-purwar** [comment]
@varisha-025 you can start working on this issue.
