### ISSUE TITLE
Add a Breakout Game

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#50]
**Breakout Game**

**Project Description**
- A very fun project which will help beginners in enhancing their skills.
- Arrow keys have to be used to control the paddle
- If the ball misses the paddle, score resets to 0.
- Check out the live version <a href="https://adit0507.github.io/Breakout-Game/" target="_blank">here</a>

**Demo:**

https://user-images.githubusercontent.com/78037846/156026660-d166a0bd-07de-4ba5-92f6-1aef4034e73e.mp4

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] HTML
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@Adit0507 you can start working on this issue.
