### ISSUE TITLE
Add a Pokemon Generator

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#51]
**Pokemon Generator**

**Project Description**
- A fun and easy to build Pokemon game which generates random Pokemons and their strengths.
- <a href="https://pokeapi.co/" target="_blank" >PokeAPI </a> was used to get the data about different Pokemons.
- Click <a href="https://adit0507.github.io/Pokemon-Card-Generator/" target="_blank">here</a> to get the live demo
<br><br>
![Pokemon](https://user-images.githubusercontent.com/78037846/156027388-97f75c3d-6ed2-46ef-a7a5-c69a3055e7f7.PNG)

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [ x] Pokemon API

**Comment by Adit0507** [comment]
I have this project ready and I raised the issue so kindly assign it to me

**Comment by khushi-purwar** [comment]
@Adit0507 you can start working on this issue.
