### ISSUE TITLE
Can made better UI for the website (I am a gssoc'22 participant )

### ISSUE THREAD

**Issue by Prajwal-ctrl** [khushi-purwar/WebDev-ProjectKart#52]
**Project name**
(Add project name over here)

**Project link**
(Provide project link over here)

**Improvements suggested**
(Write the improvements you are suggesting over here)

**Comment by RajatBhaskare7** [comment]
assign me this task

**Comment by khushi-purwar** [comment]
@Prajwal-ctrl  you can start working on this issue.

**Comment by Prajwal-ctrl** [comment]
Thank you @khushi-purwar  for assigning

**Comment by Prajwal-ctrl** [comment]
@khushi-purwar thanks for assigning . can you make this issue under GSSOC '22 please as i am GSSOC 22 participant

**Comment by Prajwal-ctrl** [comment]
hii @khushi-purwar  i am not able to push my branch its giving 403 error

**Comment by Prajwal-ctrl** [comment]
@khushi-purwar  @RajatBhaskare7  @Gurdeep475  @nirbhay12345   can you guys help me with this 

![Screenshot (375)](https://user-images.githubusercontent.com/63673431/156628189-cde8ddbb-f018-4aee-bd97-a0fba6d8cd58.png)

**Comment by Gurdeep475** [comment]
@Prajwal-ctrl I think origin is pointing to Original Repository not your forked one. Try to add new remote repository pointing to your forked repository and then push changes to that repository

**Comment by Prajwal-ctrl** [comment]
so should i change the repo name and then push it

**Comment by Gurdeep475** [comment]
> so should i change the repo name and then push it

No, just type git remote add origin2 your_forked_repo_link and then push it to origin2 and then make a pull request.

**Comment by Prajwal-ctrl** [comment]
yeah it worksed Thanks a lot 😃

**Comment by Prajwal-ctrl** [comment]
![Screenshot (377)](https://user-images.githubusercontent.com/63673431/156633077-8056248e-bfd1-494d-9bba-f2743be06a9e.png)
![Screenshot (376)](https://user-images.githubusercontent.com/63673431/156633085-e583d525-436e-4679-a17c-dfdfccb7088a.png)
![Screenshot (378)](https://user-images.githubusercontent.com/63673431/156633089-8f164e6c-91ce-40d6-91c1-084a79cbce5c.png)



Here are some screeshots 


Thanks @Gurdeep475  @khushi-purwar

**Comment by Gurdeep475** [comment]
> yeah it worksed Thanks a lot 😃

Mention not bro 😃

**Comment by Prajwal-ctrl** [comment]
@khushi-purwar any updates ?

**Comment by Prajwal-ctrl** [comment]
hii @khushi-purwar  any changes or updates regarding PR
