### ISSUE TITLE
Add a Tic Tac Toe Game

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#53]
**Tic Tac Toe Game**

**Project Description**

- A simple tic tac toe game which looks pretty simple but provides a good insight in JS.
- Game can be restarted at any point. 
- Live Version: https://adit0507.github.io/Tic-Tac-Toe/

![Tic-Tac-Toe](https://user-images.githubusercontent.com/78037846/156028863-b9f14a9f-8e3f-4167-98f1-6ca55b8acf95.PNG)

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Anish1411** [comment]
hey , i want to work on this assign it to me

**Comment by Bhawna147** [comment]
@khushi-purwar I want to work on this issue under GSSOC'22. Please assign this to me.

**Comment by Adit0507** [comment]
I raised the issue and I want to work on this

**Comment by khushi-purwar** [comment]
@Adit0507 you can start working on this issue.
