### ISSUE TITLE
Rock Paper Scissors Game

### ISSUE THREAD

**Issue by AnIkeT126** [khushi-purwar/WebDev-ProjectKart#535]
**Project title**

Rock Paper Scissors Game

**Project Description**

A DOM-based rock paper scissors JavaScript Game, that aims to take you through the nostalgia.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Mrjoy832** [comment]
https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/36.Rock-Paper-Scissors
already there

**Comment by AnIkeT126** [comment]
@Mrjoy832 it's a different approach
