### ISSUE TITLE
Add an E-Commerce Sneaker Site

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#54]
**Sneaker Site**

**Project Description**
- A really cool shoe site with a lot of features, eg: By clicking on "Buy Now" a modal opens in which the user can enter their information.
- Checkout the site <a href="https://adit0507.github.io/Sneaker-Site/" >here </a>

Demo: 
https://user-images.githubusercontent.com/78037846/156029925-d16a69f3-fc60-4a6a-b0de-206b2e6367da.mp4

**Stack**:  
- [] Html
- [] CSS
- [] JavaScript

**Comment by Anish1411** [comment]
Hey @Adit0507 , i want to work on this , assign it to me under gssoc'22.

**Comment by Adit0507** [comment]
I'm a contributor, and I raised the issue so I wish to work on this

**Comment by khushi-purwar** [comment]
@Adit0507 you have raised many issue. But at a time , only 3 issues will be assigned to a contributor.

**Comment by khushi-purwar** [comment]
> Hey @Adit0507 , i want to work on this , assign it to me under gssoc'22.

@Anish1411 you can create any other issue.

**Comment by Adit0507** [comment]
> @Adit0507 you have raised many issue. But at a time , only 3 issues will be assigned to a contributor. First you can complete those issue, then I will assign it to you.

Yes

**Comment by Adit0507** [comment]
I have finished my previous 3 issues, now you can assign me this one
