### ISSUE TITLE
Add a Custom Ice Cream Maker

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#55]
**Custom Ice Cream Maker**

**Project Description**
- Change the color of the scoop and toppings using the buttons.
- Check out the project <a href="https://adit0507.github.io/Custom-IceCream-Maker/" target="_blank">here</a>
<br>

https://user-images.githubusercontent.com/78037846/156030809-01767008-004e-49a2-af4f-cb8b48f561e4.mp4

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@Adit0507 you have raised many issue. But at a time , only 3 issues will be assigned to a contributor.
First you can complete those issue, then I will assign it to you.

**Comment by Adit0507** [comment]
Plz assign me
