### ISSUE TITLE
Add a Candy Crush Clone

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#56]
**Candy Crush Clone**
(Write project title over here)

**Project Description**

- Works exactly like the original game.
- Has a score counter to keep count of the candies crushed.
- Live version: https://adit0507.github.io/Candy-Crush/

![Candy-Crush](https://user-images.githubusercontent.com/78037846/156031776-6a7759df-74cc-4b62-b08e-9d97638d8e77.PNG)

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by SwarupKMondal** [comment]
Hey, I am a participant of GSSoC'22. I want to work on this project. I will make this candy crush clone. Please assign this issue to me.

**Comment by Adit0507** [comment]
I have this project ready and I was the one who raised it so kindly issue it to me

**Comment by khushi-purwar** [comment]
@Adit0507 you have raised many issue. But at a time , only 3 issues will be assigned to a contributor.
First you can complete those issue, then I will assign it to you.

**Comment by khushi-purwar** [comment]
> Hey, I am a participant of GSSoC'22. I want to work on this project. Please assign this issue to me.

@SwarupKMondal you can raise any other issue

**Comment by Adit0507** [comment]
Can u assign me this one plz
