### ISSUE TITLE
Add a Pong Game

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#57]
**Pong Game**

**Project Description**
- A fun and challenging game in which the user is playing against the computer
- Background color keeps changing throughout the game.

![Pong-Game](https://user-images.githubusercontent.com/78037846/156032216-664df4b6-7cd6-4eb9-89e2-5ed70889b728.PNG)

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@Adit0507 you have raised many issue. But at a time , only 3 issues will be assigned to a contributor.
First you can complete those issue, then I will assign it to you.

**Comment by Adit0507** [comment]
Plz assign me
