### ISSUE TITLE
Add a Dictionary App

### ISSUE THREAD

**Issue by Adit0507** [khushi-purwar/WebDev-ProjectKart#58]
**Dictionary App**

**Project Description**
- Free Dictionary API is used.
- The use of the word is also demonstrated in a sentence.
- Live Site: https://adit0507.github.io/Dictionary-App/

![Dictionary](https://user-images.githubusercontent.com/78037846/156034060-6059e6ad-9516-45d9-8602-9a5035f62e38.PNG)

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@Adit0507 you have raised many issue. But at a time , only 3 issues will be assigned to a contributor.
First you can complete those issue, then I will assign it to you.
