### ISSUE TITLE
Add 2048 Game

### ISSUE THREAD

**Issue by AviralSheoran** [khushi-purwar/WebDev-ProjectKart#59]
**Project title**
2048 Game

**Project Description**
A game of 2048 in vanilla JavaScript, HTML and CSS

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

## 
Hello, I'm a GSSo'C 2022 Contributor,
Please assign me this issue, I want to add **2048 Game**

**Comment by khushi-purwar** [comment]
@AviralSheoran you can start working on this issue.
