### ISSUE TITLE
Adding a Tic Tac Toe Game

### ISSUE THREAD

**Issue by LiQuiD-404** [khushi-purwar/WebDev-ProjectKart#602]
**Project title**
 Tic Tac Toe Game

**Project Description**
A simple  Tic Tac Toe Game built using HTML, CSS, and Javascript.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by BIKRAM-SAHA** [comment]
Hi @amyra98, this issue was opened a long time ago. I would love to volunteer to work on this issue if it is open for grab.

**Comment by LiQuiD-404** [comment]
@BIKRAM-SAHA I have already notified the mentors regarding the delay in submission. Kindly make a new issue.
