### ISSUE TITLE
Simon Game

### ISSUE THREAD

**Issue by Ravnoor12** [khushi-purwar/WebDev-ProjectKart#62]
**Project title**
Simon Game

**Project Description**
It is game in which players must repeat random sequences of lights by pressing the colored pads in the correct order. Level keeps increasing as long as player is repeating the correct sequence.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [X] JavaScript

**Comment by Ravnoor12** [comment]
@khushi-purwar I want to work on this issue under GSSoC '22. Please assign this issue to me.

**Comment by khushi-purwar** [comment]
@Ravnoor12 you can start working on this issue.

**Comment by Ravnoor12** [comment]
I am a contributor at GSSoC-2022. Kindly review it and merge it.
