### ISSUE TITLE
Spotify Clone

### ISSUE THREAD

**Issue by Jyo561** [khushi-purwar/WebDev-ProjectKart#63]
**Project title**
Spotify Clone

**Project Description**
clone of spotify

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] VueJS

**Comment by khushi-purwar** [comment]
@Jyo561 you can start working on this issue.

**Comment by Jyo561** [comment]
Can you assign GSSoC22 to it
