### ISSUE TITLE
Netflix Clone

### ISSUE THREAD

**Issue by Jyo561** [khushi-purwar/WebDev-ProjectKart#64]
**Project title**
Netflix Clone

**Project Description**
its a clone of Netflix

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] Svelte Js

**Comment by aroramrinaal** [comment]
Could you please give a detailed description of this **issue** .
So that I can start working on it.

**Comment by Jyo561** [comment]
i am going to work on it so i created this issue

**Comment by khushi-purwar** [comment]
@Jyo561 you can start working on this issue.

**Comment by Jyo561** [comment]
Can you assign GSSoC22 to it
