### ISSUE TITLE
Repository Website Enhancement

### ISSUE THREAD

**Issue by XZANATOL** [khushi-purwar/WebDev-ProjectKart#65]
**Project name**
WebDev-ProjectKart Github-Pages site

**Improvements suggested**
The current page have a lot of empty space that can be put in use to make the site more stylish so that it improves both UI and UX.

I'm ready to provide a demo design to what's in my mind if the idea is accepted. but for how I'm going to do it, then I have 2 methods.
1) Simple: Using a CSS file and make use of media queries.
2) Complex: Going to use Bootstrap 5.

Issue created under GSSoC'22 contributions.

**Comment by Priyal168** [comment]
Hi, I would like to contribute in this

**Comment by khushi-purwar** [comment]
@XZANATOL this issue is already raised by someone. You can raise any other issue.
