### ISSUE TITLE
Improving Password Generator project

### ISSUE THREAD

**Issue by devgirlcodes** [khushi-purwar/WebDev-ProjectKart#67]
**Project name**
Password Generator

**Project link**
[Password Generator](https://khushi-purwar.github.io/WebDev-ProjectKart/01.Password_Generator/)

**Problem**
The field `password length` is a required field but it is not indicated to the user.

**Improvements suggested**
- [x] 1. Add Required field `*` against `password length` field
- [x] 2. Add a pop-up of 'required field' in case a user submits before entering the length
- [ ] 3. Add a drop-down with integers in the password length to make it easier for user to select the length

![Screenshot 2022-03-01 105353](https://user-images.githubusercontent.com/99732684/156110145-c77209e2-ebf5-4ee1-82af-057609ef7026.png)

**Comment by devgirlcodes** [comment]
@khushi-purwar can I get this issue assigned to myself?

**Comment by khushi-purwar** [comment]
@devgirlcodes you can start working on this issue.
