### ISSUE TITLE
QR code generator in javascript

### ISSUE THREAD

**Issue by srinjoy-26** [khushi-purwar/WebDev-ProjectKart#678]
**Project title**
QR code generator in javascript

**Project Description**
QR code generator in javascript

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by AnIkeT126** [comment]
@srinjoy-26 This issue has already been made and assigned and PR has been sent.
Please make a new issue and work on it.

**Comment by srinjoy-26** [comment]
> @srinjoy-26 This issue has already been made and assigned and PR has been sent. Please make a new issue and work on it.

The project for which PR has been made is a QR code 'scanner' . The one I'm making is a QR code 'generator' . Both are different

**Comment by AnIkeT126** [comment]
> > @srinjoy-26 This issue has already been made and assigned and PR has been sent. Please make a new issue and work on it.
> 
> The project for which PR has been made is a QR code 'scanner' . The one I'm making is a QR code 'generator' . Both are different

Check Issue #609, it was made before this, and hence u cant make this as per the rules of GSSoC'22
