### ISSUE TITLE
A Crypto Currency Project 

### ISSUE THREAD

**Issue by Abh1shekSingh** [khushi-purwar/WebDev-ProjectKart#69]
**Project title**
CryptoRush

**Project Description**
In this project user can view data related to about 100 crypto currencies in the world. It can be made using API and reactjs 

**Stack**:  
REACTJS
MATERIAL UI
API 
CSS

**Comment by Abh1shekSingh** [comment]
@khushi-purwar  HI I WOULD LOVE TO WORK ON THIS PROJECT PLEASE ASSIGN THIS TO ME

**Comment by khushi-purwar** [comment]
@Abh1shekSingh you can start working on this issue.

**Comment by bosedipayan** [comment]
Hey @khushi-purwar  , I would like to work on this issue and already I'm working on it. Please, assign it to me.

**Comment by bosedipayan** [comment]
Project title
Crypto Price App

Project Description
In this project user can view data related to prices and symbol on all crypto currencies in the world. It can be made using API and reactjs

Stack:
REACTJS
API
CSS

**Comment by Abh1shekSingh** [comment]
She assigned me... So I am working on it. Please find another issue to work
on. ☺️

**Comment by Abh1shekSingh** [comment]
hi @khushi-purwar  I have successully fix the issue #69 by addign crypto application . I have closed this pull request before to do some changes to it. Thank for giving and considering.
