### ISSUE TITLE
Adding a new project, headlines

### ISSUE THREAD

**Issue by abaran803** [khushi-purwar/WebDev-ProjectKart#7]
**Project title**
Headlines | Top 10 news

**Project Description**
A project, which asks a user to enter a location and fetch the top 10 news headlines. By default, the headline of the current location will be shown. I am going to use news API for it.

**Stack**:
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
Ok @abaran803, you can work on this project.

**Comment by abaran803** [comment]
Hi @khushi-purwar, I am not able to add this project because there is a limit on the number of fetches by the API provider for a free account, which is 100 fetches per day. And now I am not able to test it. Do you know any news provider API, in which no limit on fetching for a free account?

**Comment by khushi-purwar** [comment]
@abaran803 , no

**Comment by abaran803** [comment]
> @abaran803 , no

Ok, I'll upload project after 24 hr

**Comment by khushi-purwar** [comment]
> > @abaran803 , no
> 
> Ok, I'll upload project after 24 hr

Ok.
