### ISSUE TITLE
Mario Game

### ISSUE THREAD

**Issue by aroramrinaal** [khushi-purwar/WebDev-ProjectKart#71]
**Project title**
Mario Game in **JavaScript** with **Kaboom.js**!.

**Project Description**
A game of Mario using JavaScript and Kaboom.js.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] JavaScript
- [x] KaboomJS

**Comment by aroramrinaal** [comment]
@khushi-purwar , I think it will be a great if you assign me this I will be using Kaboom, which is a Javascript game programming library that helps you to  make games fast and fun.

**Comment by aroramrinaal** [comment]
I am a GSSOC'22 **Participant**.

**Comment by khushi-purwar** [comment]
@aroramrinaal you can start working on this issue.

**Comment by aroramrinaal** [comment]
> @aroramrinaal you can start working on this issue.

Thanks.
