### ISSUE TITLE
Adding A google homepage clone

### ISSUE THREAD

**Issue by rajprem4214** [khushi-purwar/WebDev-ProjectKart#72]
**Project title**
Adding Google Homepage clone

**Project Description**
Google Clone that works like google search Engine.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [ ] ReactJS

**Comment by khushi-purwar** [comment]
@rajprem4214 you can start working on this issue.
