### ISSUE TITLE
Adding SpaceX Website Clone

### ISSUE THREAD

**Issue by LiQuiD-404** [khushi-purwar/WebDev-ProjectKart#725]
**Project title**
SpaceX Website Clone

**Project Description**
SpaceX Website Clone using HTML, CSS and Javascript.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by yash-25log** [comment]
@gurjeetsinghvirdee may i work on this?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee may i work on this?

Sure
