### ISSUE TITLE
Create a Apple India UI Clone

### ISSUE THREAD

**Issue by Kumar-laxmi** [khushi-purwar/WebDev-ProjectKart#730]
**Project title**
This is a UI Clone of Apple India

**Project Description**
This project would be implemented using HTML, CSS, JS, BootStrap Framework

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [X] Html
- [X] CSS
- [X] JavaScript
- [] ReactJS

**Comment by LiQuiD-404** [comment]
I am already working on this issue. #708

**Comment by Kumar-laxmi** [comment]
> I am already working on this issue. #708

Oh I didn't see that

**Comment by LiQuiD-404** [comment]
It's alright. : )
