### ISSUE TITLE
Add URL Shortener

### ISSUE THREAD

**Issue by Gurdeep475** [khushi-purwar/WebDev-ProjectKart#74]
**Project title**
URL Shortener

**Project Description**
It shrinks large URLs into small ones

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] Node.Js

**Comment by Gurdeep475** [comment]
I would like to work on this project under GSSOC'22. Please assign it to me

**Comment by khushi-purwar** [comment]
@Gurdeep475  This issue is already by someone , You can open any other issue.
