### ISSUE TITLE
I want to add a GST calculator.

### ISSUE THREAD

**Issue by Anchita15** [khushi-purwar/WebDev-ProjectKart#75]
I have made this GST calculator using HTML, CSS, JS.
Its responsive.
Live - https://anchita15.github.io/GSTcalculator/
<img width="955" alt="Screenshot 2022-03-01 150533" src="https://user-images.githubusercontent.com/83870242/156145217-b5fe9ec7-0140-4dc6-9969-7f5f24cdd20b.png">

**Comment by khushi-purwar** [comment]
@Anchita15 you can start working on this issue.

**Comment by Anchita15** [comment]
Thanks!
