### ISSUE TITLE
I will add a new register page

### ISSUE THREAD

**Issue by ahmadjubair33** [khushi-purwar/WebDev-ProjectKart#76]
**Project title**
(Register page)

**Project Description**
(It is a register page in which we have three field name, email, password as well as check box of term and conditions)

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] Bootstrap
- [x] Angular

Hi @khushi-purwar Please assign it to me 
![Screenshot from 2022-03-01 15-25-58](https://user-images.githubusercontent.com/89836059/156147161-edd36eea-5a8f-45df-a670-b389afb82f23.jpg)

**Comment by khushi-purwar** [comment]
@ahmadjubair33 you can start working on this issue.

**Comment by ahmadjubair33** [comment]
Hi, @khushi-purwar I have raised a PR for issue #76 please Review it and merge it. Thank You!!!!!
