### ISSUE TITLE
Falling_Ball_Game

### ISSUE THREAD

**Issue by priyanshu688** [khushi-purwar/WebDev-ProjectKart#769]
**Project title**
(Falling Ball Game)

**Project Description**
(This is just a simple falling ball game built using the JavaScript language.)

**Stack**:  
- [x] JavaScript

**Comment by priyanshu688** [comment]
@amyra98 Can you please check this out - https://github.com/priyanshu688/WebDev-ProjectKart/commit/eba492be7ed9c27dccc1ec79645a18957c38db8b

**Comment by priyanshu688** [comment]
Actually I don't know why this PR got merge in some other issue of this same project. I have added the project. and shared the link above.

**Comment by Sulagna-Dutta-Roy** [comment]
I can made this project . Can I work on this Issue @amyra98
