### ISSUE TITLE
Portfolio Website

### ISSUE THREAD

**Issue by mishramuskaan24** [khushi-purwar/WebDev-ProjectKart#77]
**Project title**
Portfolio Website

**Project Description**
Hi @khushi-purwar. I am currently learning HTML, CSS and JAVASCRIPT and would love to add my portfolio website as a part of your project. Please assign me with this issue so that I can start working on it  

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@mishramuskaan24 the portfolio issue is already raised by someone. You can raise a different issue
