### ISSUE TITLE
Adding Birthday CountDown Timer 

### ISSUE THREAD

**Issue by Nanshi29** [khushi-purwar/WebDev-ProjectKart#78]
**Project title**
Birthday CountDown Timer

**Project Description**
A CountDown Timer will be set for every dates and it wishes you Happy birthday.
Please assign this to me. Im a contributor at GSSoC'22.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [ ] ReactJS

**Comment by khushi-purwar** [comment]
@Nanshi29 you can start working on this issue.
