### ISSUE TITLE
Differrent GLassmorphism Card UI Design with Vanila 

### ISSUE THREAD

**Issue by CoderSahil128** [khushi-purwar/WebDev-ProjectKart#79]
I am a contributor from GSSoC - 22. I can create different kinds of glassmorphism card UI designs like glowing gradients and etc. and can add some effects like hover and tilt effects.so Please assign this issue to me

https://user-images.githubusercontent.com/97339865/156155012-4f9c5ee4-b50f-4398-9f27-893ca349870a.mp4

**Comment by khushi-purwar** [comment]
@CoderSahil128 you can start working on this issue.

**Comment by CoderSahil128** [comment]
> @CoderSahil128 you can start working on this issue.

Thank you for assigning this issue. I'll make the PR and will send it tomorrow.

**Comment by CoderSahil128** [comment]
@khushi-purwar Kindly please tell me when would u gonna label this issue?
