### ISSUE TITLE
Atomic animation

### ISSUE THREAD

**Issue by srinjoy-26** [khushi-purwar/WebDev-ProjectKart#802]
**Project title**

Atom animation
**Project Description**
Atom animation

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS

**Comment by Sulagna-Dutta-Roy** [comment]
@amyra98 Hiii, Can I work on this Issue ? Then assign me please

**Comment by srinjoy-26** [comment]
> @amyra98 Hiii, Can I work on this Issue ? Then assign me please
My project is ready 😄

**Comment by Sulagna-Dutta-Roy** [comment]
Oh okay. Good Luck
