### ISSUE TITLE
ASCII Generator

### ISSUE THREAD

**Issue by eswarbhageerath** [khushi-purwar/WebDev-ProjectKart#823]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is ASCII Values Generator.

The idea behind this project
This is a very mini project which can be used to know the ASCII Value of any character entered as input

###How does it work
Whenever you enter a number in the input box and click submit, we can see the result in a box below .

![ss1](https://user-images.githubusercontent.com/76146796/163524946-55ae776c-fda7-4d6c-93a6-7fcac58245fd.png)
![ss2](https://user-images.githubusercontent.com/76146796/163524949-8c44a40c-54d2-4166-a77c-bb6bcf589d23.png)

**Comment by eswarbhageerath** [comment]
@khushi-purwar Please review my PR

**Comment by pushpanjali-10** [comment]
I want to work on this issue, and can work on it on an urgent basis, can you please assign it to me??

**Comment by eswarbhageerath** [comment]
@khushi-purwar Please review my PR

**Comment by eswarbhageerath** [comment]
@amyra98  Please help me with this problem.....
Initially, this issue has level 1 label, I got score 15 added.
But now as you made it level 3, I should see my score increased by 30 (45-15).
But I can not see the increased score in latest GSSOC Leaderboard.
