### ISSUE TITLE
Windows 11 Using HTML, CSS & JavaScript

### ISSUE THREAD

**Issue by mishramuskaan24** [khushi-purwar/WebDev-ProjectKart#83]
**Project title**
Windows 11 Using HTML, CSS & JavaScript

**Project Description**
Hi @khushi-purwar, I would love to create Windows 11 lookalike using HTML, CSS, and JavaScript. Please assign me to this issue so that I can start working.
Thank You

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by mishramuskaan24** [comment]
@khushi-purwar please assign me with this issue. I am a participant in GSSOC'22. 
Thank You

**Comment by khushi-purwar** [comment]
@mishramuskaan24 you can start working on it.
