### ISSUE TITLE
Fortune Cookie Generator

### ISSUE THREAD

**Issue by AnIkeT126** [khushi-purwar/WebDev-ProjectKart#839]
**Project title**

Fortune Cookie Generator

**Project Description**

A web-app based fully responsive Fortune Cookie Generator.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by abhilipsasahoo03** [comment]
Hi @khushi-purwar @meinhoonharsh I would like to let you know that this project has been plagiarized from the Fortune Cookie generator project I submitted to Arpit Jain's Amazing Js Projects. Here is the link: https://github.com/arpit456jain/Amazing-Js-Projects/pull/447
You can compare the code, the layout is also the same.
