### ISSUE TITLE
Score_Keeper

### ISSUE THREAD

**Issue by sm-sourabh** [khushi-purwar/WebDev-ProjectKart#84]
**Project title**
Keep the score of TWO players

**Project Description**
This project uses JavaScript to make a Score Calulctor which stores and updates the score of the players playing ping pong.

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by sm-sourabh** [comment]
Hey ! I am a participant under GSSOC'22 . Can you assign this issue to me ?

**Comment by itaintkevin** [comment]
Hi @khushi-purwar, I'm a GSSOC'22 Contributor. I would love to work on this issue. Please assign it to me if u don't mind.

**Comment by khushi-purwar** [comment]
@sm-sourabh you can start working on it
