### ISSUE TITLE
Will add a new Project

### ISSUE THREAD

**Issue by Chirantanbanik** [khushi-purwar/WebDev-ProjectKart#86]
**Project title**
Calculator

**Project Description**
A Calculator made with HTML and CSS. The design of the Calculator is in Glass Morphism UI.
Deployed link: https://chirantanbanik.github.io/Calculator/

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

1. [x]Html
2. [x]CSS

**Comment by Chirantanbanik** [comment]
I will add up this project!

**Comment by khushi-purwar** [comment]
@Chirantanbanik you can start working on it
