### ISSUE TITLE
I will add a Linkedin UI clone created with HTML and CSS

### ISSUE THREAD

**Issue by AmolShelke2** [khushi-purwar/WebDev-ProjectKart#866]
**Project title**
(Linkedln UI clone)

**Project Description**
(LinkedIn UI clone created with HTML and CSS it is a clone of LinkedIn homepage it doesn't consist of any  functionality because it was only created using HTML and CSS please assign me this issue to work on.)

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS

![Screenshot-1](https://user-images.githubusercontent.com/95171638/163802815-52596cf9-a59f-42f4-a1c4-6134967f744d.png)

@khushi-purwar kindly review this issue
@gurjeetsinghvirdee Kindly review this issue

**Comment by gurjeetsinghvirdee** [comment]
Someone already created LinkedIn PR, so I'm closing thi issue
