### ISSUE TITLE
Adding a Chat Bot

### ISSUE THREAD

**Issue by LiQuiD-404** [khushi-purwar/WebDev-ProjectKart#893]
**Project title**
Chat Bot

**Project Description**
Chat Bot using HTML, CSS, and Javascript.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by AastikSharma05** [comment]
@amyra98 can you please assign this issue to me

**Comment by LiQuiD-404** [comment]
@AastikSharma05 This issue is already assigned to me. Kindly make a new issue.

**Comment by navyasharma0203** [comment]
Can I work on this??
