### ISSUE TITLE
I'm a participant of GSSoC 22 and I'd like to contribute to this project

### ISSUE THREAD

**Issue by sauradip007** [khushi-purwar/WebDev-ProjectKart#90]
**Project title**
Movies App

**Project Description**
A movies aoo created with html css and vanilla js which shows the current repertoire of movies running along with their release date and IMDB ratings in a poster like format , made using TMDB API.

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
Movie App issue is already raised. You can create any other issue.

**Comment by sauradip007** [comment]
I believe that is movie recommendation , mine has a collection of movies along with search functionality as well.
