### ISSUE TITLE
Movie Website

### ISSUE THREAD

**Issue by mishramuskaan24** [khushi-purwar/WebDev-ProjectKart#91]
**Project title**
Creating a movie website using HTML, CSS, and JavaScript.

**Project Description**
Hi @khushi-purwar, I would love to create a classic movie website using HTML, CSS, and JavaScript. Please assign me to this issue so that I can start working.I am really excited to work on this project
Thank You

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@mishramuskaan24 you can start working on it
