### ISSUE TITLE
Add Whatsapp Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [khushi-purwar/WebDev-ProjectKart#917]
**Project title**
Whatsapp Clone

**Project Description**
It's a react Project

**Stack**:  
And in order to tick the check box just put x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] ReactJS

**Comment by sampavaranasi** [comment]
@khushi-purwar https://github.com/Rayman-Sodhi/Clone-IT/issues/172
