### ISSUE TITLE
Want to improve UI of digital clock

### ISSUE THREAD

**Issue by iamrahulmahato** [khushi-purwar/WebDev-ProjectKart#92]
**Project name**
(Digital clock)

**Project link**
([Provide project link over here](https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/05.Digital_Clock))

**Improvements suggested**
(Let me enhance or improve the UI, Please assign this to me. Im a contributor at GSSoC'22.)

**Comment by khushi-purwar** [comment]
@iamrahulmahato you can start working on it

**Comment by iamrahulmahato** [comment]
@khushi-purwar The PR is made #279 . Kindly review and merge it.
Thank You
