### ISSUE TITLE
Improve the UI of Password_Generator

### ISSUE THREAD

**Issue by iamrahulmahato** [khushi-purwar/WebDev-ProjectKart#93]
**Project name**
(Password_Generator)

**Project link**
([Provide project link over here](https://github.com/khushi-purwar/WebDev-ProjectKart/tree/master/01.Password_Generator))

**Improvements suggested**
(1.Improve the UI,2.adding scrolling function in generate password,Im a contributor at GSSoC'22)

**Comment by ShivanshCharak** [comment]
can i work on this issue

**Comment by khushigupta123** [comment]
@khushi-purwar can I work on this issue please.

**Comment by iamrahulmahato** [comment]
The PR is made #208. Kindly review and merge it.
Thank You
