### ISSUE TITLE
Adding a Credit Card Generator

### ISSUE THREAD

**Issue by LiQuiD-404** [khushi-purwar/WebDev-ProjectKart#931]
**Project title**
Credit Card Generator

**Project Description**
A Credit Card Generator which can generate Name, Card Number, expiry date, and CVV

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Sulagna-Dutta-Roy** [comment]
Can I work on this Issue? @gurjeetsinghvirdee

**Comment by LiQuiD-404** [comment]
@Sulagna-Dutta-Roy I am already working on this issue. Kindly make your own issues

**Comment by Sulagna-Dutta-Roy** [comment]
Okay. Good Luck.
