### ISSUE TITLE
Adding Grocery site

### ISSUE THREAD

**Issue by bosedipayan** [khushi-purwar/WebDev-ProjectKart#94]
**Project title**
(Gromart - Grocery website)

**Project Description**
(A Grocery website which provides daily needs with required items.
Please assign this to me. I'm a contributor at GSSoC'22.)

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by khushi-purwar** [comment]
@bosedipayan you can start working on it
