### ISSUE TITLE
Rock Paper Scissors Game

### ISSUE THREAD

**Issue by shr-code** [khushi-purwar/WebDev-ProjectKart#945]
**Rock-Paper-Scissors-Game**

**Project Description**
The rock, paper, and scissors game is a simple and entertaining game in which both players have to choose rock, paper, or scissors. It can only end in a draw or with one player winning and the other losing. I'll use JavaScript to create a game in which the player competes against the computer.  Between rock, paper, and scissors, the player must choose one choice. From the computer's side, a random option will be created, and the winner will receive one point each time.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] CSS
- [x] JavaScript
- [] ReactJS

**Comment by shr-code** [comment]
@amyra98  @khushi-purwar this issue was already merged so should I pick  choose other issues?

**Comment by shr-code** [comment]
@khushi-purwar ??

**Comment by khushi-purwar** [comment]
> @khushi-purwar ??

Yes please choose other issue or create your own issue.
