### ISSUE TITLE
Bing Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [khushi-purwar/WebDev-ProjectKart#968]
**Project title**
Bing Website Clone

**Project Description**
This is a Famous search engine powered by microsoft

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript
- [x] ReactJS

**Comment by gurjeetsinghvirdee** [comment]
Assigned u @Sulagna-Dutta-Roy

**Comment by gurjeetsinghvirdee** [comment]
OHo Sorry don't make a PR we are not accepting😅

**Comment by gurjeetsinghvirdee** [comment]
@Sulagna-Dutta-Roy
