### ISSUE TITLE
Ping Pong Game 

### ISSUE THREAD

**Issue by harshraj29** [khushi-purwar/WebDev-ProjectKart#97]
**Project title**
Ping Pong Game

**Project Description**
This Ping Pong Game is made using Javascript for beginners.User can use this web app to play ping pong game

**Stack**:  

- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by harshraj29** [comment]
I am a GSSoC '22 participant. Please assign me this issue.

**Comment by rv602** [comment]
hello @khushi-purwar, Rajagopalan this side. 
I wish to work on creating a ping pong game using HTML, CSS, JavaScript.
Below I have attached a prototype of what I wish to build.

![WhatsApp Image 2022-03-02 at 12 32 34 AM](https://user-images.githubusercontent.com/92572013/156232703-edde6197-d498-4e26-a7fb-93307f4cdef6.jpeg)

At the beginning of the game, the ball's motion will be randomised. When the ball hits the upper or lower part of the screen, it'll bounce at a random angle towards the opponent’s side. 
If a player fails to deflect the ball and it hits his wall, the opponent's score is incremented by one.
