### ISSUE TITLE
I want to add Rock-Paper-Scissors game

### ISSUE THREAD

**Issue by Anish1411** [khushi-purwar/WebDev-ProjectKart#98]
**Project title**
Rock-Paper-Scissors game

**Project Description**
Rock-Paper-Scissors game with fully functionality.

**Stack**:  
- [x] Html
- [x] CSS
- [x] JavaScript

**Comment by Anish1411** [comment]
I am a GSSoC '22 contributor ,  please assign me this issue.

**Comment by khushi-purwar** [comment]
@Anish1411 you can start working on it

**Comment by Anish1411** [comment]
hey @khushi-purwar  i have amde the pr #147 , Do have a look . If any changes do let me know.
